<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="Current">

  <PropertyGroup>
    <TargetFrameworks>$(WindowsFramework)</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <OutputPath>..\..\Output\Activities\Credentials\</OutputPath>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <NoWarn>CS1591</NoWarn>
    <AssemblyName>UiPath.Credentials.Activities.API</AssemblyName>
    <RootNamespace>UiPath.Credentials.Activities.API</RootNamespace>
    <PackageId>UiPath.Credentials.Activities.API.Implementation</PackageId>
    <IsPackable>false</IsPackable>
    <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='$(WindowsFramework)'">
    <DefineConstants>$(DefineConstants);NETCORE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="UiPath.Activities.Api"/>
    <PackageReference Include="UiPath.Activities.Contracts">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="UiPath.CodedWorkflows"/>
    <PackageReference Include="UiPath.Platform"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UiPath.Credentials.Activities\UiPath.Credentials.Activities.csproj" />
  </ItemGroup>

</Project>
