trigger:
  branches:
    include:
      - master
      - develop
      - release/*
      - support/*
  paths:
    include:
      - Activities/FTP/*
      - Activities/Activities.FTP.sln

variables:
  majorVersion: '2'
  minorVersion: '2'
  patchVersion: '0'
  revision: $[counter(variables['patchVersion'], 1)] #this will get reset when minor gets bumped.
  versionSuffix: 'alpha.$(revision)'
  versionNumber: '$(majorVersion).$(minorVersion).$(patchVersion)'
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
   versionSuffix: ''
  ${{ if contains(variables['Build.SourceBranchName'], 'release') }}:
   versionSuffix: 'beta.$(revision)'

pr:
  branches:
    include:
      - master
      - develop
      - release/*
      - support/*
      - feature/*
  paths:
    include:
      - Activities/FTP/*
      - Activities/Activities.FTP.sln

jobs:
  - template: "../.pipelines/jobs/ci.yml"
    parameters:
      BuildProject: "../Activities.FTP.sln"
      BuildConfiguration: "Release"
      BuildPlatform: "AnyCPU"
      rootPath: $(Build.SourcesDirectory)\Activities\FTP\
      packagesDirectory: $(Build.SourcesDirectory)\Activities\packages\
      restoreDependencies: 
        - "UiPath.FTP.Activities/UiPath.FTP.Activities.csproj"
        - "UiPath.FTP/UiPath.FTP.csproj"      
      versionReference: "FTPAssemblyInfo.cs"
      versionNumber: ${{ variables.versionNumber }}
      versionSuffix: ${{ variables.versionSuffix }}
