trigger:
  batch: true
  branches:
    include:
    - develop
    - masters/FTP
    - release/FTP/*
    - support/FTP/*
  paths:
    include:
    - Activities/FTP/*
    - Activities/Activities.FTP.sln
    - Activities/Directory.build.targets
    - Activities/Shared/*
    - Activities/Tools/*

pr:
  branches:
    include:
    - develop
    - masters/FTP
    - release/FTP/*
    - support/FTP/*
  paths:
    include:
    - Activities/FTP/*
    - Activities/Activities.FTP.sln
    - Activities/Directory.build.targets
    - Activities/Shared/*
    - Activities/Tools/*

variables:
  - template: ..\.pipelines\variables\variables.yml

stages:
  - template: ..\.pipelines\templates\stage.start.yml
    parameters:
      projectName: 'FTP'
      solutionPath: '$(SolutionsPath)/Activities.FTP.sln'
      sdkBuild: false
      enableCDStages: false
      hasQaPackages: false
      preTestRun:
      - task: UseDotNet@2
        displayName: 'Install .NET 6 SDK'
        inputs:
          packageType: 'sdk'
          version: '6.0.x'


