<Project>
	<PropertyGroup>
		<!-- Make sure that we don't overlook assembly version conflicts -->
		<MSBuildWarningsAsErrors>MSB3277</MSBuildWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Update="UiPath.Workflow" Version="6.0.0-20240320-03" />
		<PackageReference Update="UiPath.Workflow.Runtime" Version="6.0.0-20240320-03" />
		<PackageReference Update="System.Activities.Core.Presentation" Version="6.0.0-20220318.2" />
		<PackageReference Update="System.Activities.Metadata" Version="6.0.0-20220831.1" PrivateAssets="All"/>
		<PackageReference Update="System.Activities.ViewModels" Version="1.0.0-20250519.7"/>
		<PackageReference Update="System.Activities" Version="5.0.0-20210615-01" />
	</ItemGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == '$(PortableFramework)' ">
		<PackageReference Update="System.Security.Cryptography.Cng" Version="4.5.2" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Update="UiPath.Robot.Api" Version="24.10.5" PrivateAssets="All" />
		<PackageReference Update="UiPath.Activities.Api" Version="24.10.5" PrivateAssets="All" />
		<PackageReference Update="UiPath.Activities.Contracts" Version="24.10.5" PrivateAssets="All" />
		<PackageReference Update="UiPath.Telemetry.Client" Version="2.1.3" PrivateAssets="All" />
		<PackageReference Update="UiPath.Platform" Version="24.10.3"/>

		<PackageReference Update="System.Drawing.Common" Version="6.0.0" />
		<PackageReference Update="System.Text.RegularExpressions" Version="4.3.1" />
		<PackageReference Update="System.Formats.Asn1" Version="8.0.1" />

		<PackageReference Update="Azure.Identity" Version="1.13.1" />
	</ItemGroup>

	<PropertyGroup>
		<DefineConstants Condition="'$(TargetFramework)' == '$(PortableFramework)'">$(DefineConstants);NETSTANDARD</DefineConstants>
	</PropertyGroup>

	<ItemGroup Condition="'$(IsTestProject)' == 'true'">
		<PackageReference Include="Moq" Version="4.18.4" />
		<PackageReference Include="Shouldly" Version="4.3.0" />
		<PackageReference Include="xunit" Version="2.9.3" />
		<PackageReference Include="xunit.abstractions" Version="2.0.3" />
		<PackageReference Include="xunit.analyzers" Version="1.21.0" />
		<PackageReference Include="xunit.assert" Version="2.9.3" />
		<PackageReference Include="xunit.core" Version="2.9.3" />
		<PackageReference Include="xunit.extensibility.core" Version="2.9.3" />
		<PackageReference Include="xunit.extensibility.execution" Version="2.9.3" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.0.2">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
		
		<PackageReference Update="Xunit.StaFact" Version="2.1.17" />
		<PackageReference Update="ReflectionMagic" Version="5.0.1" />
		<PackageReference Update="System.Net.Http" Version="4.3.4" />
		<PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4" />
		<PackageReference Include="System.ValueTuple" Version="4.5.0" />
	</ItemGroup>

	<!-- For whatever reason, with "Fast UpToDate" VS option ON, changes are not detected properly 
	Eg. obj/Debug/net6-0/refint/ .. is not copied to /obj/Debug/net6-0/ref even if there are changes
	This causes package not to be generated even if there are changes (rebuild is necessary)
	This is very annoying when developing -->
	<Target Name="UpdateObjRefIfNeeded" AfterTargets="PostBuildEvent" Condition="$(ConfigurationName) == Debug">
		<ItemGroup>
			<RefintFile Include="$([System.IO.Path]::GetFullPath('$(IntermediateOutputPath)'))/refint/$(TargetFileName)" />
			<RefFile Include="$([System.IO.Path]::GetFullPath('$(IntermediateOutputPath)'))/ref/$(TargetFileName)" />
		</ItemGroup>
		<Copy
		  SourceFiles="@(RefintFile)"
		  DestinationFiles="@(RefFile)"
		  SkipUnchangedFiles="true"
		  OverwriteReadOnlyFiles="true"
		  Condition="Exists('%(RefintFile.Identity)')" />
	</Target>
</Project>