resources:
  repositories:
  - repository: common
    type: github
    name: UiPath/AzurePipelinesTemplates
    ref: refs/tags/uipath.community.activities.1.3.0
    endpoint: "GitHub connection"
  - repository: automationTests
    type: github
    name: UiPath/AzurePipelinesTemplates
    ref: refs/tags/uipath.waitforbuild.1.0.3
    endpoint: "GitHub connection"

trigger:
  batch: true
  branches:
    include:
    - develop
    - masters/Cryptography
    - release/Cryptography/*
    - support/Cryptography/*
  paths:
    include:
    - Activities/Cryptography/*
    - Activities/Activities.Cryptography.sln
    - Activities/Shared/*
    - Activities/Tools/*

pr:
  branches:
    include:
    - develop
    - masters/Cryptography
    - release/Cryptography/*
    - support/Cryptography/*
  paths:
    include:
    - Activities/Cryptography/*
    - Activities/Activities.Cryptography.sln
    - Activities/Shared/*
    - Activities/Tools/*

variables:
  - template: ..\.pipelines\variables\variables.yml

stages:
  - template: Activities/stage.start.yml@common
    parameters:
      projectName: 'Cryptography'
      solutionPath: '$(SolutionsPath)/Activities.Cryptography.sln'
      buildPoolName: 'activities-build'
      testPoolName: 'activities-build'
      sonarKeyPrefix: 'CommunityActivities'
      sdkBuild: true
      enableCDStages: false
      hasQaPackages: false

  - stage: BuildCryptographyRuntimeTests
    displayName: 'Build Cryptography Runtime Tests'
    dependsOn:
      - Build
    jobs:
    - template: ../.pipelines/jobs/stage.build.runtime.tests.yml
      parameters:
        robotVersion: $(TestsStudioVersion)
        studioProjectPath: 'Activities/Cryptography/UiPath.Cryptography.Activities.RuntimeTests/project.json'
        buildForWindows: true
        buildForPortable: true
        packageUnderTestName: 'UiPath.Cryptography.Activities'

  - stage: RunCryptographyRuntimeTestsWindows
    displayName: 'Run Cryptography Runtime Tests Windows'
    dependsOn:
      - BuildCryptographyRuntimeTests
    jobs:
    - template: ../.pipelines/jobs/stage.run.runtime.tests.windows.yml
      parameters:
        robotVersion: $(TestsStudioVersion)

  - stage: RunCryptographyRuntimeTestsPortable
    displayName: 'Run Cryptography Runtime Tests Portable'
    dependsOn:
      - BuildCryptographyRuntimeTests
    jobs:
    - template: ../.pipelines/jobs/stage.run.runtime.tests.portable.yml
      parameters:
        robotVersion: $(TestsStudioVersion)
