resources:
  repositories:
  - repository: common
    type: github
    name: UiPath/AzurePipelinesTemplates
    ref: refs/tags/uipath.community.activities.1.3.0
    endpoint: "GitHub connection"

trigger:
  batch: true
  branches:
    include:
    - develop
    - masters/Cryptography
    - release/Cryptography/*
    - support/Cryptography/*
  paths:
    include:
    - Activities/Cryptography/*
    - Activities/Activities.Cryptography.sln
    - Activities/Shared/*
    - Activities/Tools/*

pr:
  branches:
    include:
    - develop
    - masters/Cryptography
    - release/Cryptography/*
    - support/Cryptography/*
  paths:
    include:
    - Activities/Cryptography/*
    - Activities/Activities.Cryptography.sln
    - Activities/Shared/*
    - Activities/Tools/*

variables:
  - template: ..\.pipelines\variables\variables.yml

stages:
  - template: Activities/stage.start.yml@common
    parameters:
      projectName: 'Cryptography'
      solutionPath: '$(SolutionsPath)/Activities.Cryptography.sln'
      buildPoolName: 'activities-build'
      testPoolName: 'activities-build'
      sonarKeyPrefix: 'CommunityActivities'
      sdkBuild: true
      enableCDStages: false
      hasQaPackages: false
