<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(PortableFramework);$(WindowsFramework)</TargetFrameworks>
    <OutputPath>..\..\OutputTests\Database\</OutputPath>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <UseWindowsForms Condition="'$(TargetFramework)'=='$(WindowsFramework)'">true</UseWindowsForms>
    <UseWPF Condition="'$(TargetFramework)'=='$(WindowsFramework)'">true</UseWPF>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='$(WindowsFramework)'">
    <DefineConstants>NETCORE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="UiPath.Activities.Api" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UiPath.Database.Activities.API\UiPath.Database.Activities.API.csproj" />
    <ProjectReference Include="..\UiPath.Database.Tests\UiPath.Database.Tests.csproj" />
  </ItemGroup>

</Project>
