trigger:
  branches:
    include:
      - masters/Credentials/*
      - develop
      - release/Credentials/*
      - support/Credentials/*
  paths:
    include:
      - Activities/Credentials/*
      - Activities/Activities.Credentials.sln

variables:
  - template: vars.yml
  - template: "../.pipelines/variables/vars.yml"


pr:
  branches:
    include:
      - master
      - develop
      - release/*
      - support/*
      - feature/*
  paths:
    include:
      - Activities/Credentials/*
      - Activities/Activities.Credentials.sln

jobs:
  - template: "../.pipelines/jobs/ci.yml"
    parameters:
      BuildProject: "../Activities.Credentials.sln"
      BuildConfiguration: "Release"
      BuildPlatform: "AnyCPU"
      rootPath: $(Build.SourcesDirectory)\Activities\Credentials\
      packagesDirectory: $(Build.SourcesDirectory)\Activities\packages\
      versionReference: "UiPath.Credentials.Activities/Properties/AssemblyInfo.cs"
      versionNumber: ${{ variables.versionNumber }}
      versionSuffix: ${{ variables.versionSuffix }}
