resources:
  repositories:
  - repository: common
    type: github
    name: UiPath/AzurePipelinesTemplates
    ref: refs/tags/uipath.community.activities.1.1.0
    endpoint: "GitHub connection"

trigger:
  batch: true
  branches:
    include:
    - develop
    - masters/Credentials
    - release/Credentials/*
    - support/Credentials/*
  paths:
    include:
    - Activities/Credentials/*
    - Activities/Activities.Credentials.sln
    - Activities/Shared/*
    - Activities/Tools/*

pr:
  branches:
    include:
    - develop
    - masters/Credentials
    - release/Credentials/*
    - support/Credentials/*
  paths:
    include:
    - Activities/Credentials/*
    - Activities/Activities.Credentials.sln
    - Activities/Shared/*
    - Activities/Tools/*

variables:
  - template: ..\.pipelines\variables\variables.yml

stages:
- stage: Clean
  jobs:
  - job:
    displayName: "Hello"
    timeoutInMinutes: 300
    pool:
      vmImage: windows-latest
    steps:
    - pwsh: |
        Write-Host "Hello"
      displayName: "Hello"

