resources:
  repositories:
  - repository: common
    type: github
    name: UiPath/AzurePipelinesTemplates
    ref: refs/tags/uipath.community.activities.1.3.0
    endpoint: "GitHub connection"

trigger:
  batch: true
  branches:
    include:
    - develop
    - masters/Credentials
    - release/Credentials/*
    - support/Credentials/*
  paths:
    include:
    - Activities/Credentials/*
    - Activities/Activities.Credentials.sln
    - Activities/Directory.build.targets
    - Activities/Shared/*
    - Activities/Tools/*

pr:
  branches:
    include:
    - develop
    - masters/Credentials
    - release/Credentials/*
    - support/Credentials/*
  paths:
    include:
    - Activities/Credentials/*
    - Activities/Activities.Credentials.sln
    - Activities/Directory.build.targets
    - Activities/Shared/*
    - Activities/Tools/*

variables:
  - template: ..\.pipelines\variables\variables.yml

stages:
  - job:
    displayName: "Hello"
    timeoutInMinutes: 300
    pool:
      vmImage: windows-latest
    steps:
    - pwsh: |
        Write-Host "Hello"
      displayName: "Hello"

  - template: Activities/stage.start.yml@common
    parameters:
      projectName: 'Credentials'
      solutionPath: '$(SolutionsPath)/Activities.Credentials.sln'
      sonarKeyPrefix: 'CommunityActivities'
      sdkBuild: false
      enableCDStages: false
      hasQaPackages: false

