trigger:
  batch: true
  branches:
    include:
    - develop
    - masters/Java
    - release/Java/*
    - support/Java/*
  paths:
    include:
    - Activities/Java/*
    - Activities/Activities.Java.sln
    - Activities/Directory.build.targets
    - Activities/Shared/*
    - Activities/Tools/*

pr:
  branches:
    include:
    - develop
    - masters/Java
    - release/Java/*
    - support/Java/*
  paths:
    include:
    - Activities/Java/*
    - Activities/Activities.Java.sln
    - Activities/Directory.build.targets
    - Activities/Shared/*
    - Activities/Tools/*

variables:
  - template: ..\.pipelines\variables\variables.yml

stages:
  - template: ..\.pipelines\templates\stage.start.yml
    parameters:
      projectName: 'Java'
      solutionPath: '$(SolutionsPath)/Activities.Java.sln'
      sonarKeyPrefix: 'CommunityActivities'
      sdkBuild: false
      enableCDStages: false
      hasQaPackages: false
      preTestRun:
      - task: UseDotNet@2
        displayName: 'Install .NET 6 SDK'
        inputs:
          packageType: 'sdk'
          version: '6.0.x'

