trigger:
  branches:
    include:
      - master
      - develop
      - release/*
      - support/*
  paths:
    include:
      - Activities/Java/*
      - Activities/Activities.Java.sln

variables:
  majorVersion: '1'
  minorVersion: '2'
  patchVersion: '0'
  revision: $[counter(variables['patchVersion'], 1)] #this will get reset when minor gets bumped.
  versionSuffix: 'alpha.$(revision)'
  versionNumber: '$(majorVersion).$(minorVersion).$(patchVersion)'
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
   versionSuffix: ''
  ${{ if contains(variables['Build.SourceBranchName'], 'release') }}:
   versionSuffix: 'beta.$(revision)'


pr:
  branches:
    include:
      - master
      - develop
      - release/*
      - support/*
      - feature/*
  paths:
    include:
      - Activities/Java/*
      - Activities/Activities.Java.sln

jobs:
  - template: "../.pipelines/jobs/ci.yml"
    parameters:
      BuildProject: "../Activities.Java.sln"
      BuildConfiguration: "Release"
      BuildPlatform: "AnyCPU"
      rootPath: $(Build.SourcesDirectory)\Activities\Java\
      packagesDirectory: $(Build.SourcesDirectory)\Activities\packages\
      restoreDependencies: 
        - "UiPath.Java/UiPath.Java.csproj"
        - "UiPath.Java.Activities/UiPath.Java.Activities.csproj"
      testList: 
        - "UiPath.Java.Test/UiPath.Java.Test.csproj"
      versionReference: "JavaPackageVersion.cs"
      versionNumber: ${{ variables.versionNumber }}
      versionSuffix: ${{ variables.versionSuffix }}

