trigger:
  branches:
    include:
      - masters/Java
      - develop
      - release/Java/*
      - support/Java/*
  paths:
    include:
      - Activities/Java/*
      - Activities/Activities.Java.sln

variables:
  - template: vars.yml
  - template: "../.pipelines/variables/vars.yml"


pr:
  branches:
    include:
      - master
      - develop
      - release/*
      - support/*
      - feature/*
  paths:
    include:
      - Activities/Java/*
      - Activities/Activities.Java.sln

jobs:
  - template: "../.pipelines/jobs/ci.yml"
    parameters:
      BuildProject: "../Activities.Java.sln"
      BuildConfiguration: "Release"
      BuildPlatform: "AnyCPU"
      rootPath: $(Build.SourcesDirectory)\Activities\Java\
      packagesDirectory: $(Build.SourcesDirectory)\Activities\packages\
      restoreDependencies: 
        - "UiPath.Java/UiPath.Java.csproj"
        - "UiPath.Java.Activities/UiPath.Java.Activities.csproj"
      testList: 
        - "UiPath.Java.Test/UiPath.Java.Test.csproj"
      versionReference: "JavaPackageVersion.cs"
      versionNumber: ${{ variables.versionNumber }}
      versionSuffix: ${{ variables.versionSuffix }}

