<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="Current">
  <PropertyGroup>
    <TargetFrameworks>$(PortableFramework);$(WindowsFramework)</TargetFrameworks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <OutputPath>..\..\Output\Activities\Database\</OutputPath>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <NoWarn>CS1591</NoWarn>
    <AssemblyName>UiPath.Database.Activities.API</AssemblyName>
    <RootNamespace>UiPath.Database.Activities.API</RootNamespace>
    <PackageId>UiPath.Database.Activities.API.Implementation</PackageId>
    <IsPackable>false</IsPackable>
    <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='$(WindowsFramework)'">
    <DefineConstants>$(DefineConstants);NETCORE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Extensions\**" />
    <EmbeddedResource Remove="Extensions\**" />
    <None Remove="Extensions\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="UiPath.Activities.Api" />
    <PackageReference Include="UiPath.Activities.Contracts">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="UiPath.CodedWorkflows" />
    <PackageReference Include="UiPath.Platform" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UiPath.Database.Activities\UiPath.Database.Activities.csproj" />
    <ProjectReference Include="..\UiPath.Database\UiPath.Database.csproj" />
  </ItemGroup>

</Project>
