trigger:
  branches:
    include:
      - master
      - develop
      - release/*
      - support/*
  paths:
    include:
      - Activities/GoogleSpreadsheet/*
      - Activities/Activities.GoogleSpreadsheet.sln

variables:
  majorVersion: '1'
  minorVersion: '2'
  patchVersion: '0'
  revision: $[counter(variables['patchVersion'], 1)] #this will get reset when minor gets bumped.
  versionSuffix: 'alpha.$(revision)'
  versionNumber: '$(majorVersion).$(minorVersion).$(patchVersion)'
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
   versionSuffix: ''
  ${{ if contains(variables['Build.SourceBranchName'], 'release') }}:
   versionSuffix: 'beta.$(revision)'


pr:
  branches:
    include:
      - master
      - develop
      - release/*
      - support/*
      - feature/*
  paths:
    include:
      - Activities/GoogleSpreadsheet/*
      - Activities/Activities.GoogleSpreadsheet.sln

jobs:
  - template: "../.pipelines/jobs/ci.yml"
    parameters:
      BuildProject: "../Activities.GoogleSpreadsheet.sln"
      BuildConfiguration: "Release"
      BuildPlatform: "AnyCPU"
      rootPath: $(Build.SourcesDirectory)\Activities\GoogleSpreadsheet\
      packagesDirectory: $(Build.SourcesDirectory)\Activities\packages\
      restoreDependencies: 
        - "GoogleSpreadsheet/GoogleSpreadsheet.csproj"
        - "GoogleSpreadsheet.Activities/GoogleSpreadsheet.Activities.csproj"
      testList: 
        - "GoogleSpreadsheet.Activities.UnitTest/GoogleSpreadsheet.Activities.UnitTest.csproj"      
      versionReference: "GoogleSpreadsheetVersion.cs"
      versionNumber: ${{ variables.versionNumber }}
      versionSuffix: ${{ variables.versionSuffix }}