parameters:
  robotVersion: ''
  beforeTestsCustomSteps: []
  afterTestsCustomSteps: []

jobs:
- job: "RunDatabaseRuntimeTestsWindows"
  displayName: "Run Database Runtime Tests Windows"
  variables:
    IntegrationTestStudioPackPath: '$(System.ArtifactsDirectory)/Packages'
    StudioProjectPath: 'Activities/Database/UiPath.Database.Runtime.Tests/project.json'
  timeoutInMinutes: 90
  pool:
    vmImage: windows-2022
  workspace:
    clean: outputs | resources | all

  steps:
  - task: UniversalPackages@0
    displayName: "Download TestRunner"
    inputs:
      command: 'download'
      downloadDirectory: "$(Build.ArtifactStagingDirectory)/TestRunner"
      vstsFeed: "UiPath-DevPackages"
      vstsFeedPackage: "uipath.testrunner"
      vstsPackageVersion: $(TestRunnerVersion)
      verbosity: 'Trace'

  - task: BuildProcessCleaner@0
     
  - task: ms-autotest.screen-resolution-utility-task.screen-resolution-utlity-task.ScreenResolutionUtility@1
    displayName: 'Set Screen Resolution'
    inputs:
      displaySettings: specific
      width: 1920
      height: 1080

  - task: Docker@2
    displayName: Login to container registry
    inputs:
      command: login
      containerRegistry: 'codedwfdemoregistry'

  - task: UseDotNet@2
    displayName: 'Use .NET SDK 8.0.x'
    inputs:
      packageType: 'sdk'
      version: '8.0.x'

  - task: DownloadPipelineArtifact@2
    displayName: "Download Packages"
    inputs:
      artifact: "Packages"
      path: "$(IntegrationTestStudioPackPath)"

  # install robot
  - template: Testing/Automation/install.msi.steps.template.yml@automationTests
    parameters:
      installType: 'machine'
      msiType: 'robot'
      msiVersion: ${{ parameters.robotVersion }}
      license: "7445-1270-1408-6250"
      installComponents: 'Robot'

  - powershell: |
      & "C:/Program Files/UiPath/Robot/UiRobot.exe" trace --enableLowLevel
    displayName: "Enable robot low level"
    failOnStderr: false
  
  - ${{ each step in parameters.beforeTestsCustomSteps }}:
    - ${{ step }}

  - powershell: |
      $filepath = Get-ChildItem $(IntegrationTestStudioPackPath)/*_windows*
      $fullPath = $filepath.FullName
      $env:MOUNT_OUTPUT="$(System.ArtifactsDirectory)"
      $(Build.ArtifactStagingDirectory)/TestRunner/uipath.studio.codedwf.tests.runner.exe run --package $fullPath --output $(System.ArtifactsDirectory) --robotPath "C:/Program Files/UiPath/Robot/UiRobot.exe"
    displayName: 'Execute tests'

  - ${{ each step in parameters.afterTestsCustomSteps }}:
    - ${{ step }}

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testRunTitle: "Windows Runtime Tests"
      testResultsFiles: '$(System.ArtifactsDirectory)/results*.trx'
      publishRunAttachments: true
      failTaskOnFailedTests: true
      mergeTestResults: true
    displayName: 'Publish Tests Results'
    condition: always()