//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiPath.FTP.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiPath_FTP_Activities {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiPath_FTP_Activities() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiPath.FTP.Activities.Properties.UiPath.FTP.Activities", typeof(UiPath_FTP_Activities).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept all certificates.
        /// </summary>
        public static string AcceptAllCertificates {
            get {
                return ResourceManager.GetString("AcceptAllCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes a file or folder from an FTP server. This activity only works if it is placed inside a Use FTP Connection activity..
        /// </summary>
        public static string Activity_Delete_Description {
            get {
                return ResourceManager.GetString("Activity_Delete_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete File or Folder.
        /// </summary>
        public static string Activity_Delete_Name {
            get {
                return ResourceManager.GetString("Activity_Delete_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote path to the file or folder.
        /// </summary>
        public static string Activity_Delete_Property_RemotePath_Description {
            get {
                return ResourceManager.GetString("Activity_Delete_Property_RemotePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File or folder to delete.
        /// </summary>
        public static string Activity_Delete_Property_RemotePath_Name {
            get {
                return ResourceManager.GetString("Activity_Delete_Property_RemotePath_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /remote/folder/file.txt.
        /// </summary>
        public static string Activity_Delete_Property_RemotePath_Placeholder {
            get {
                return ResourceManager.GetString("Activity_Delete_Property_RemotePath_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks whether a folder exists on an FTP server. This activity only works if it is placed inside a Use FTP Connection activity..
        /// </summary>
        public static string Activity_DirectoryExists_Description {
            get {
                return ResourceManager.GetString("Activity_DirectoryExists_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check If Folder Exists.
        /// </summary>
        public static string Activity_DirectoryExists_Name {
            get {
                return ResourceManager.GetString("Activity_DirectoryExists_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A boolean variable that states whether the indicated directory was found or not..
        /// </summary>
        public static string Activity_DirectoryExists_Property_Exists_Description {
            get {
                return ResourceManager.GetString("Activity_DirectoryExists_Property_Exists_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exists.
        /// </summary>
        public static string Activity_DirectoryExists_Property_Exists_Name {
            get {
                return ResourceManager.GetString("Activity_DirectoryExists_Property_Exists_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote folder path to check.
        /// </summary>
        public static string Activity_DirectoryExists_Property_RemotePath_Description {
            get {
                return ResourceManager.GetString("Activity_DirectoryExists_Property_RemotePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder path.
        /// </summary>
        public static string Activity_DirectoryExists_Property_RemotePath_Name {
            get {
                return ResourceManager.GetString("Activity_DirectoryExists_Property_RemotePath_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /remote/folder.
        /// </summary>
        public static string Activity_DirectoryExists_Property_RemotePath_Placeholder {
            get {
                return ResourceManager.GetString("Activity_DirectoryExists_Property_RemotePath_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads the specified files from an FTP server to the specified local folder. This activity only works if it is placed inside a Use FTP Connection activity..
        /// </summary>
        public static string Activity_DownloadFiles_Description {
            get {
                return ResourceManager.GetString("Activity_DownloadFiles_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Files.
        /// </summary>
        public static string Activity_DownloadFiles_Name {
            get {
                return ResourceManager.GetString("Activity_DownloadFiles_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If turned on, the folder path is created locally in case it does not already exist..
        /// </summary>
        public static string Activity_DownloadFiles_Property_Create_Description {
            get {
                return ResourceManager.GetString("Activity_DownloadFiles_Property_Create_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create folder if missing.
        /// </summary>
        public static string Activity_DownloadFiles_Property_Create_Name {
            get {
                return ResourceManager.GetString("Activity_DownloadFiles_Property_Create_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The local path for the files that are to be downloaded..
        /// </summary>
        public static string Activity_DownloadFiles_Property_LocalPath_Description {
            get {
                return ResourceManager.GetString("Activity_DownloadFiles_Property_LocalPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where to download.
        /// </summary>
        public static string Activity_DownloadFiles_Property_LocalPath_Name {
            get {
                return ResourceManager.GetString("Activity_DownloadFiles_Property_LocalPath_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Local\folder.
        /// </summary>
        public static string Activity_DownloadFiles_Property_LocalPath_Placeholder {
            get {
                return ResourceManager.GetString("Activity_DownloadFiles_Property_LocalPath_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If turned on, the files are overwritten locally if they are already stored there..
        /// </summary>
        public static string Activity_DownloadFiles_Property_Overwrite_Description {
            get {
                return ResourceManager.GetString("Activity_DownloadFiles_Property_Overwrite_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite existing files.
        /// </summary>
        public static string Activity_DownloadFiles_Property_Overwrite_Name {
            get {
                return ResourceManager.GetString("Activity_DownloadFiles_Property_Overwrite_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If turned on, the folders are downloaded with their respective subfolders..
        /// </summary>
        public static string Activity_DownloadFiles_Property_Recursive_Description {
            get {
                return ResourceManager.GetString("Activity_DownloadFiles_Property_Recursive_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include subfolders.
        /// </summary>
        public static string Activity_DownloadFiles_Property_Recursive_Name {
            get {
                return ResourceManager.GetString("Activity_DownloadFiles_Property_Recursive_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path of the files on the FTP server that are to be downloaded..
        /// </summary>
        public static string Activity_DownloadFiles_Property_RemotePath_Description {
            get {
                return ResourceManager.GetString("Activity_DownloadFiles_Property_RemotePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to files to download.
        /// </summary>
        public static string Activity_DownloadFiles_Property_RemotePath_Name {
            get {
                return ResourceManager.GetString("Activity_DownloadFiles_Property_RemotePath_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /remote/folder.
        /// </summary>
        public static string Activity_DownloadFiles_Property_RemotePath_Placeholder {
            get {
                return ResourceManager.GetString("Activity_DownloadFiles_Property_RemotePath_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates a collection of the files and folders found on the FTP server. Subfolders can also be included by turning on Include subfolders. This activity only works if it is placed inside a Use FTP Connection activity..
        /// </summary>
        public static string Activity_EnumerateObjects_Description {
            get {
                return ResourceManager.GetString("Activity_EnumerateObjects_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Files and Folders.
        /// </summary>
        public static string Activity_EnumerateObjects_Name {
            get {
                return ResourceManager.GetString("Activity_EnumerateObjects_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection of files and folders found on the FTP server..
        /// </summary>
        public static string Activity_EnumerateObjects_Property_Files_Description {
            get {
                return ResourceManager.GetString("Activity_EnumerateObjects_Property_Files_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files and folders.
        /// </summary>
        public static string Activity_EnumerateObjects_Property_Files_Name {
            get {
                return ResourceManager.GetString("Activity_EnumerateObjects_Property_Files_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters items based on type (what is selected will be included).
        /// </summary>
        public static string Activity_EnumerateObjects_Property_Filter_Description {
            get {
                return ResourceManager.GetString("Activity_EnumerateObjects_Property_Filter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item types to include.
        /// </summary>
        public static string Activity_EnumerateObjects_Property_Filter_Name {
            get {
                return ResourceManager.GetString("Activity_EnumerateObjects_Property_Filter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the item types to include.
        /// </summary>
        public static string Activity_EnumerateObjects_Property_Filter_Placeholder {
            get {
                return ResourceManager.GetString("Activity_EnumerateObjects_Property_Filter_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If turned on, the subfolders are also included in the listing..
        /// </summary>
        public static string Activity_EnumerateObjects_Property_Recursive_Description {
            get {
                return ResourceManager.GetString("Activity_EnumerateObjects_Property_Recursive_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include subfolders.
        /// </summary>
        public static string Activity_EnumerateObjects_Property_Recursive_Name {
            get {
                return ResourceManager.GetString("Activity_EnumerateObjects_Property_Recursive_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path of the folder on the FTP server whose contents are listed..
        /// </summary>
        public static string Activity_EnumerateObjects_Property_RemotePath_Description {
            get {
                return ResourceManager.GetString("Activity_EnumerateObjects_Property_RemotePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder path.
        /// </summary>
        public static string Activity_EnumerateObjects_Property_RemotePath_Name {
            get {
                return ResourceManager.GetString("Activity_EnumerateObjects_Property_RemotePath_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /remote/folder.
        /// </summary>
        public static string Activity_EnumerateObjects_Property_RemotePath_Placeholder {
            get {
                return ResourceManager.GetString("Activity_EnumerateObjects_Property_RemotePath_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks whether a file exists in the specified FTP folder. This activity only works if it is placed inside a Use FTP Connection activity..
        /// </summary>
        public static string Activity_FileExists_Description {
            get {
                return ResourceManager.GetString("Activity_FileExists_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check If File Exists.
        /// </summary>
        public static string Activity_FileExists_Name {
            get {
                return ResourceManager.GetString("Activity_FileExists_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A boolean variable that states whether the indicated file was found or not..
        /// </summary>
        public static string Activity_FileExists_Property_Exists_Description {
            get {
                return ResourceManager.GetString("Activity_FileExists_Property_Exists_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exists.
        /// </summary>
        public static string Activity_FileExists_Property_Exists_Name {
            get {
                return ResourceManager.GetString("Activity_FileExists_Property_Exists_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote file path to check.
        /// </summary>
        public static string Activity_FileExists_Property_RemotePath_Description {
            get {
                return ResourceManager.GetString("Activity_FileExists_Property_RemotePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path.
        /// </summary>
        public static string Activity_FileExists_Property_RemotePath_Name {
            get {
                return ResourceManager.GetString("Activity_FileExists_Property_RemotePath_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /remote/folder/file.txt.
        /// </summary>
        public static string Activity_FileExists_Property_RemotePath_Placeholder {
            get {
                return ResourceManager.GetString("Activity_FileExists_Property_RemotePath_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves an item on an FTP server to a different remote path. This activity only works if it is placed inside a Use FTP Connection activity..
        /// </summary>
        public static string Activity_MoveItem_Description {
            get {
                return ResourceManager.GetString("Activity_MoveItem_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move File or Folder.
        /// </summary>
        public static string Activity_MoveItem_Name {
            get {
                return ResourceManager.GetString("Activity_MoveItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if the automation should continue even when the activity throws an error..
        /// </summary>
        public static string Activity_MoveItem_Property_ContinueOnError_Description {
            get {
                return ResourceManager.GetString("Activity_MoveItem_Property_ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue On Error.
        /// </summary>
        public static string Activity_MoveItem_Property_ContinueOnError_Name {
            get {
                return ResourceManager.GetString("Activity_MoveItem_Property_ContinueOnError_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new path where to move the item.
        /// </summary>
        public static string Activity_MoveItem_Property_NewPath_Description {
            get {
                return ResourceManager.GetString("Activity_MoveItem_Property_NewPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where to move.
        /// </summary>
        public static string Activity_MoveItem_Property_NewPath_Name {
            get {
                return ResourceManager.GetString("Activity_MoveItem_Property_NewPath_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /remote/new-folder/file.txt.
        /// </summary>
        public static string Activity_MoveItem_Property_NewPath_Placeholder {
            get {
                return ResourceManager.GetString("Activity_MoveItem_Property_NewPath_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If turned on, the files are overwritten in the new remote folder if they are already stored there..
        /// </summary>
        public static string Activity_MoveItem_Property_Overwrite_Description {
            get {
                return ResourceManager.GetString("Activity_MoveItem_Property_Overwrite_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite existing files.
        /// </summary>
        public static string Activity_MoveItem_Property_Overwrite_Name {
            get {
                return ResourceManager.GetString("Activity_MoveItem_Property_Overwrite_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote path.
        /// </summary>
        public static string Activity_MoveItem_Property_RemotePath_Description {
            get {
                return ResourceManager.GetString("Activity_MoveItem_Property_RemotePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File or folder to move.
        /// </summary>
        public static string Activity_MoveItem_Property_RemotePath_Name {
            get {
                return ResourceManager.GetString("Activity_MoveItem_Property_RemotePath_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /remote/folder/file.txt.
        /// </summary>
        public static string Activity_MoveItem_Property_RemotePath_Placeholder {
            get {
                return ResourceManager.GetString("Activity_MoveItem_Property_RemotePath_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploads files to an FTP server. This activity only works if it is placed inside a Use FTP Connection activity..
        /// </summary>
        public static string Activity_UploadFiles_Description {
            get {
                return ResourceManager.GetString("Activity_UploadFiles_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Files.
        /// </summary>
        public static string Activity_UploadFiles_Name {
            get {
                return ResourceManager.GetString("Activity_UploadFiles_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If turned on, the folder path is created on the FTP server in case it does not already exist..
        /// </summary>
        public static string Activity_UploadFiles_Property_Create_Description {
            get {
                return ResourceManager.GetString("Activity_UploadFiles_Property_Create_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create folder if missing.
        /// </summary>
        public static string Activity_UploadFiles_Property_Create_Name {
            get {
                return ResourceManager.GetString("Activity_UploadFiles_Property_Create_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local path.
        /// </summary>
        public static string Activity_UploadFiles_Property_LocalPath_Description {
            get {
                return ResourceManager.GetString("Activity_UploadFiles_Property_LocalPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files to upload.
        /// </summary>
        public static string Activity_UploadFiles_Property_LocalPath_Name {
            get {
                return ResourceManager.GetString("Activity_UploadFiles_Property_LocalPath_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Local\folder.
        /// </summary>
        public static string Activity_UploadFiles_Property_LocalPath_Placeholder {
            get {
                return ResourceManager.GetString("Activity_UploadFiles_Property_LocalPath_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If turned on, the files are overwritten on the FTP server if they are already stored there..
        /// </summary>
        public static string Activity_UploadFiles_Property_Overwrite_Description {
            get {
                return ResourceManager.GetString("Activity_UploadFiles_Property_Overwrite_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite existing files.
        /// </summary>
        public static string Activity_UploadFiles_Property_Overwrite_Name {
            get {
                return ResourceManager.GetString("Activity_UploadFiles_Property_Overwrite_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If turned on, the folders are uploaded with their respective subfolders..
        /// </summary>
        public static string Activity_UploadFiles_Property_Recursive_Description {
            get {
                return ResourceManager.GetString("Activity_UploadFiles_Property_Recursive_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include subfolders.
        /// </summary>
        public static string Activity_UploadFiles_Property_Recursive_Name {
            get {
                return ResourceManager.GetString("Activity_UploadFiles_Property_Recursive_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote path.
        /// </summary>
        public static string Activity_UploadFiles_Property_RemotePath_Description {
            get {
                return ResourceManager.GetString("Activity_UploadFiles_Property_RemotePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where to upload.
        /// </summary>
        public static string Activity_UploadFiles_Property_RemotePath_Name {
            get {
                return ResourceManager.GetString("Activity_UploadFiles_Property_RemotePath_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /remote/folder.
        /// </summary>
        public static string Activity_UploadFiles_Property_RemotePath_Placeholder {
            get {
                return ResourceManager.GetString("Activity_UploadFiles_Property_RemotePath_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connects to FTP server and provides a scope for other FTP activities..
        /// </summary>
        public static string Activity_WithFtpSession_Description {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use FTP Connection.
        /// </summary>
        public static string Activity_WithFtpSession_Name {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If turned on, all certificates are accepted, including the ones that are expired or not verified..
        /// </summary>
        public static string Activity_WithFtpSession_Property_AcceptAllCertificates_Description {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_AcceptAllCertificates_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept all certificates.
        /// </summary>
        public static string Activity_WithFtpSession_Property_AcceptAllCertificates_Name {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_AcceptAllCertificates_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The switch for certificate password input mode.
        /// </summary>
        public static string Activity_WithFtpSession_Property_CertificatePasswordInputModeSwitch_Description {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_CertificatePasswordInputModeSwitch_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecurePasswordInputModeSwitch.
        /// </summary>
        public static string Activity_WithFtpSession_Property_CertificatePasswordInputModeSwitch_Name {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_CertificatePasswordInputModeSwitch_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password for the client certificate..
        /// </summary>
        public static string Activity_WithFtpSession_Property_ClientCertificatePassword_Description {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_ClientCertificatePassword_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client certificate password.
        /// </summary>
        public static string Activity_WithFtpSession_Property_ClientCertificatePassword_Name {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_ClientCertificatePassword_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the certificate used to verify the identity of the client..
        /// </summary>
        public static string Activity_WithFtpSession_Property_ClientCertificatePath_Description {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_ClientCertificatePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client certificate file.
        /// </summary>
        public static string Activity_WithFtpSession_Property_ClientCertificatePath_Name {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_ClientCertificatePath_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Certificates\client.pfx.
        /// </summary>
        public static string Activity_WithFtpSession_Property_ClientCertificatePath_Placeholder {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_ClientCertificatePath_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password for client certificate in secure string format.
        /// </summary>
        public static string Activity_WithFtpSession_Property_ClientCertificateSecurePassword_Description {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_ClientCertificateSecurePassword_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client certificate secure password.
        /// </summary>
        public static string Activity_WithFtpSession_Property_ClientCertificateSecurePassword_Name {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_ClientCertificateSecurePassword_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies if the automation should continue even when the activity throws an error..
        /// </summary>
        public static string Activity_WithFtpSession_Property_ContinueOnError_Description {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue on error.
        /// </summary>
        public static string Activity_WithFtpSession_Property_ContinueOnError_Name {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_ContinueOnError_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use FTP Connection.
        /// </summary>
        public static string Activity_WithFtpSession_Property_DisplayName_Name {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_DisplayName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switches to the FTPS protocol. Choose one of the two available options: Explicit or Implicit..
        /// </summary>
        public static string Activity_WithFtpSession_Property_FtpsMode_Description {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_FtpsMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTPS mode.
        /// </summary>
        public static string Activity_WithFtpSession_Property_FtpsMode_Name {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_FtpsMode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL of the FTP server that you want to connect to..
        /// </summary>
        public static string Activity_WithFtpSession_Property_Host_Description {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_Host_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string Activity_WithFtpSession_Property_Host_Name {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_Host_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp.example.com.
        /// </summary>
        public static string Activity_WithFtpSession_Property_Host_Placeholder {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_Host_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password that will be used to connect to the FTP server..
        /// </summary>
        public static string Activity_WithFtpSession_Property_Password_Description {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_Password_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Activity_WithFtpSession_Property_Password_Name {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_Password_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The switch for password input mode.
        /// </summary>
        public static string Activity_WithFtpSession_Property_PasswordInputModeSwitch_Description {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_PasswordInputModeSwitch_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordInputModeSwitch.
        /// </summary>
        public static string Activity_WithFtpSession_Property_PasswordInputModeSwitch_Name {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_PasswordInputModeSwitch_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The port of the FTP server that you want to connect to..
        /// </summary>
        public static string Activity_WithFtpSession_Property_Port_Description {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_Port_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Activity_WithFtpSession_Property_Port_Name {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_Port_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21 for FTP, 22 for SFTP.
        /// </summary>
        public static string Activity_WithFtpSession_Property_Port_Placeholder {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_Port_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password used for proxy if authentication is required.
        /// </summary>
        public static string Activity_WithFtpSession_Property_ProxyPassword_Description {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_ProxyPassword_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy password.
        /// </summary>
        public static string Activity_WithFtpSession_Property_ProxyPassword_Name {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_ProxyPassword_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy port number.
        /// </summary>
        public static string Activity_WithFtpSession_Property_ProxyPort_Description {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_ProxyPort_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy port.
        /// </summary>
        public static string Activity_WithFtpSession_Property_ProxyPort_Name {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_ProxyPort_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The proxy password in secure string format.
        /// </summary>
        public static string Activity_WithFtpSession_Property_ProxySecurePassword_Description {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_ProxySecurePassword_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy secure password.
        /// </summary>
        public static string Activity_WithFtpSession_Property_ProxySecurePassword_Name {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_ProxySecurePassword_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy host name.
        /// </summary>
        public static string Activity_WithFtpSession_Property_ProxyServer_Description {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_ProxyServer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy host.
        /// </summary>
        public static string Activity_WithFtpSession_Property_ProxyServer_Name {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_ProxyServer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to proxy.example.com.
        /// </summary>
        public static string Activity_WithFtpSession_Property_ProxyServer_Placeholder {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_ProxyServer_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of proxy.
        /// </summary>
        public static string Activity_WithFtpSession_Property_ProxyType_Description {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_ProxyType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy type.
        /// </summary>
        public static string Activity_WithFtpSession_Property_ProxyType_Name {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_ProxyType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user used for proxy if authentication is required.
        /// </summary>
        public static string Activity_WithFtpSession_Property_ProxyUser_Description {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_ProxyUser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy username.
        /// </summary>
        public static string Activity_WithFtpSession_Property_ProxyUser_Name {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_ProxyUser_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password in secure string format.
        /// </summary>
        public static string Activity_WithFtpSession_Property_SecurePassword_Description {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_SecurePassword_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure password.
        /// </summary>
        public static string Activity_WithFtpSession_Property_SecurePassword_Name {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_SecurePassword_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the SSL protocol to be used for the FTPS connection.
        /// </summary>
        public static string Activity_WithFtpSession_Property_SslProtocols_Description {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_SslProtocols_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL protocols.
        /// </summary>
        public static string Activity_WithFtpSession_Property_SslProtocols_Name {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_SslProtocols_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto: negotiate the best available protocol.
        /// </summary>
        public static string Activity_WithFtpSession_Property_SslProtocols_Placeholder {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_SslProtocols_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timeout value (in milliseconds) for the FTP/SFTP connection. If not set, the default timeout of the underlying library is used..
        /// </summary>
        public static string Activity_WithFtpSession_Property_Timeout_Description {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_Timeout_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string Activity_WithFtpSession_Property_Timeout_Name {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_Timeout_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Milliseconds.
        /// </summary>
        public static string Activity_WithFtpSession_Property_Timeout_Placeholder {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_Timeout_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If turned on, the username and password fields are ignored, and a standard anonymous user is used instead..
        /// </summary>
        public static string Activity_WithFtpSession_Property_UseAnonymousLogin_Description {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_UseAnonymousLogin_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use anonymous login.
        /// </summary>
        public static string Activity_WithFtpSession_Property_UseAnonymousLogin_Name {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_UseAnonymousLogin_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username that will be used to connect to the FTP server..
        /// </summary>
        public static string Activity_WithFtpSession_Property_Username_Description {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_Username_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Activity_WithFtpSession_Property_Username_Name {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_Username_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on to use the SFTP transfer protocol..
        /// </summary>
        public static string Activity_WithFtpSession_Property_UseSftp_Description {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_UseSftp_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SFTP.
        /// </summary>
        public static string Activity_WithFtpSession_Property_UseSftp_Name {
            get {
                return ResourceManager.GetString("Activity_WithFtpSession_Property_UseSftp_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ActivitySynonymDeleteFileOrFolder {
            get {
                return ResourceManager.GetString("ActivitySynonymDeleteFileOrFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move Item.
        /// </summary>
        public static string ActivitySynonymMoveFileOrFolder {
            get {
                return ResourceManager.GetString("ActivitySynonymMoveFileOrFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to With FTP connection.
        /// </summary>
        public static string ActivitySynonymUseFtpConnection {
            get {
                return ResourceManager.GetString("ActivitySynonymUseFtpConnection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Credentials.
        /// </summary>
        public static string Category_Credentials_Name {
            get {
                return ResourceManager.GetString("Category_Credentials_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        public static string Category_Misc_Name {
            get {
                return ResourceManager.GetString("Category_Misc_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Category_Others_Name {
            get {
                return ResourceManager.GetString("Category_Others_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Category_Output_Name {
            get {
                return ResourceManager.GetString("Category_Output_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        public static string Category_Principal_Name {
            get {
                return ResourceManager.GetString("Category_Principal_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Category_Security_Name {
            get {
                return ResourceManager.GetString("Category_Security_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string Category_Server_Name {
            get {
                return ResourceManager.GetString("Category_Server_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client certificate password.
        /// </summary>
        public static string ClientCertificatePassword {
            get {
                return ResourceManager.GetString("ClientCertificatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client certificate password.
        /// </summary>
        public static string ClientCertificatePasswordDescription {
            get {
                return ResourceManager.GetString("ClientCertificatePasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client certificate path.
        /// </summary>
        public static string ClientCertificatePath {
            get {
                return ResourceManager.GetString("ClientCertificatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the Private key in PKCS #1 PEM format.
        /// </summary>
        public static string ClientCertificatePathDesc {
            get {
                return ResourceManager.GetString("ClientCertificatePathDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue on error.
        /// </summary>
        public static string ContinueOnError {
            get {
                return ResourceManager.GetString("ContinueOnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials.
        /// </summary>
        public static string Credentials {
            get {
                return ResourceManager.GetString("Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string DefaultBodyName {
            get {
                return ResourceManager.GetString("DefaultBodyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteDescription {
            get {
                return ResourceManager.GetString("DeleteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteDisplayName {
            get {
                return ResourceManager.GetString("DeleteDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Exists.
        /// </summary>
        public static string DirectoryExistsDescription {
            get {
                return ResourceManager.GetString("DirectoryExistsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Exists.
        /// </summary>
        public static string DirectoryExistsDisplayName {
            get {
                return ResourceManager.GetString("DirectoryExistsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Files.
        /// </summary>
        public static string DownloadFilesDescription {
            get {
                return ResourceManager.GetString("DownloadFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Files.
        /// </summary>
        public static string DownloadFilesDisplayName {
            get {
                return ResourceManager.GetString("DownloadFilesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout must be greater than or equal to 0..
        /// </summary>
        public static string InvalidTimeoutException {
            get {
                return ResourceManager.GetString("InvalidTimeoutException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Username cannot be empty..
        /// </summary>
        public static string EmptyUsernameException {
            get {
                return ResourceManager.GetString("EmptyUsernameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerate Objects.
        /// </summary>
        public static string EnumerateObjectsDescription {
            get {
                return ResourceManager.GetString("EnumerateObjectsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumerate Objects.
        /// </summary>
        public static string EnumerateObjectsDisplayName {
            get {
                return ResourceManager.GetString("EnumerateObjectsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exists.
        /// </summary>
        public static string Exists {
            get {
                return ResourceManager.GetString("Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required extension could not be found..
        /// </summary>
        public static string ExtensionNotFoundException {
            get {
                return ResourceManager.GetString("ExtensionNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Exists.
        /// </summary>
        public static string FileExistsDescription {
            get {
                return ResourceManager.GetString("FileExistsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Exists.
        /// </summary>
        public static string FileExistsDisplayName {
            get {
                return ResourceManager.GetString("FileExistsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string FilesDescription {
            get {
                return ResourceManager.GetString("FilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No FTP session found..
        /// </summary>
        public static string FTPSessionNotFoundException {
            get {
                return ResourceManager.GetString("FTPSessionNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTPS mode.
        /// </summary>
        public static string FtpsMode {
            get {
                return ResourceManager.GetString("FtpsMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string HostDescription {
            get {
                return ResourceManager.GetString("HostDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source path points to a directory but the destination path points to a file..
        /// </summary>
        public static string IncompatiblePathsException {
            get {
                return ResourceManager.GetString("IncompatiblePathsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local path.
        /// </summary>
        public static string LocalPath {
            get {
                return ResourceManager.GetString("LocalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local path.
        /// </summary>
        public static string LocalPathDescription {
            get {
                return ResourceManager.GetString("LocalPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Item.
        /// </summary>
        public static string MoveItemDescription {
            get {
                return ResourceManager.GetString("MoveItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Item.
        /// </summary>
        public static string MoveItemDisplayName {
            get {
                return ResourceManager.GetString("MoveItemDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New remote path.
        /// </summary>
        public static string NewPath {
            get {
                return ResourceManager.GetString("NewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New path.
        /// </summary>
        public static string NewPathDescription {
            get {
                return ResourceManager.GetString("NewPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid authentication method found: You need to supply either Private Key file (and optionally passphrase) or Password.
        /// </summary>
        public static string NoValidAuthenticationMethod {
            get {
                return ResourceManager.GetString("NoValidAuthenticationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Obsolete).
        /// </summary>
        public static string ObsoleteEnumValue {
            get {
                return ResourceManager.GetString("ObsoleteEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An FTP session was already provided for the current context..
        /// </summary>
        public static string OneFTPSessionPerContextException {
            get {
                return ResourceManager.GetString("OneFTPSessionPerContextException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite.
        /// </summary>
        public static string Overwrite {
            get {
                return ResourceManager.GetString("Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordDescription {
            get {
                return ResourceManager.GetString("PasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path "{0}" not found..
        /// </summary>
        public static string PathNotFoundException {
            get {
                return ResourceManager.GetString("PathNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string PortDescription {
            get {
                return ResourceManager.GetString("PortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy.
        /// </summary>
        public static string Proxy {
            get {
                return ResourceManager.GetString("Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include subfolders.
        /// </summary>
        public static string Recursive {
            get {
                return ResourceManager.GetString("Recursive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote path.
        /// </summary>
        public static string RemotePath {
            get {
                return ResourceManager.GetString("RemotePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote path.
        /// </summary>
        public static string RemotePathDescription {
            get {
                return ResourceManager.GetString("RemotePathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL protocols.
        /// </summary>
        public static string SslProtocols {
            get {
                return ResourceManager.GetString("SslProtocols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported object type encountered..
        /// </summary>
        public static string UnsupportedObjectTypeException {
            get {
                return ResourceManager.GetString("UnsupportedObjectTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Files.
        /// </summary>
        public static string UploadFilesDescription {
            get {
                return ResourceManager.GetString("UploadFilesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Files.
        /// </summary>
        public static string UploadFilesDisplayName {
            get {
                return ResourceManager.GetString("UploadFilesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use anonymous login.
        /// </summary>
        public static string UseAnonymousLogin {
            get {
                return ResourceManager.GetString("UseAnonymousLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When this box is checked, the username and password fields are ignored, and a standard anonymous user is used instead..
        /// </summary>
        public static string UseAnonymousLoginDescription {
            get {
                return ResourceManager.GetString("UseAnonymousLoginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UsernameDescription {
            get {
                return ResourceManager.GetString("UsernameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SFTP.
        /// </summary>
        public static string UseSftp {
            get {
                return ResourceManager.GetString("UseSftp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientCertificatePassword and ClientCertificateSecurePassword must not be both null.
        /// </summary>
        public static string ValidationError_ClientCertificatePasswordFieldsNotNull {
            get {
                return ResourceManager.GetString("ValidationError_ClientCertificatePasswordFieldsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and SecurePassword must not be both null.
        /// </summary>
        public static string ValidationError_PasswordFieldsNotNull {
            get {
                return ResourceManager.GetString("ValidationError_PasswordFieldsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity is valid only inside {0}.
        /// </summary>
        public static string ValidationError_ValidateParentError {
            get {
                return ResourceManager.GetString("ValidationError_ValidateParentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a value for {0}..
        /// </summary>
        public static string ValidationErrorFormat {
            get {
                return ResourceManager.GetString("ValidationErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Ftp Session.
        /// </summary>
        public static string WithFtpSessionDescription {
            get {
                return ResourceManager.GetString("WithFtpSessionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Ftp Session.
        /// </summary>
        public static string WithFtpSessionDisplayName {
            get {
                return ResourceManager.GetString("WithFtpSessionDisplayName", resourceCulture);
            }
        }
    }
}
