<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(PortableFramework)</TargetFramework>
    <OutputPath>..\..\OutputTests\Python\</OutputPath>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="UiPath.Workflow" />
    <PackageReference Include="UiPath.Activities.Contracts" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UiPath.Python.Activities\UiPath.Python.Activities.csproj" />
    <ProjectReference Include="..\UiPath.Python.Tests\UiPath.Python.Tests.csproj" />
    <ProjectReference Include="..\..\Shared\UiPath.TestUtils\UiPath.TestUtils.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\xunit.runner.json">
      <Link>xunit.runner.json</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
