//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiPath.Credentials.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiPath_Credentials_Activities {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiPath_Credentials_Activities() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiPath.Credentials.Activities.Properties.UiPath.Credentials.Activities", typeof(UiPath_Credentials_Activities).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Credentials.
        /// </summary>
        public static string Activity_AddCredential_Property_AddCredentialDescription_Description {
            get {
                return ResourceManager.GetString("Activity_AddCredential_Property_AddCredentialDescription_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Credentials.
        /// </summary>
        public static string Activity_AddCredential_Property_AddCredentialDisplayName_Name {
            get {
                return ResourceManager.GetString("Activity_AddCredential_Property_AddCredentialDisplayName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential Type - The only supported values for Credential Type are &apos;Generic&apos; or &apos;DomainPassword&apos;.
        /// </summary>
        public static string Activity_AddCredential_Property_CredentialType_Description {
            get {
                return ResourceManager.GetString("Activity_AddCredential_Property_CredentialType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential Type.
        /// </summary>
        public static string Activity_AddCredential_Property_CredentialType_Name {
            get {
                return ResourceManager.GetString("Activity_AddCredential_Property_CredentialType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Credentials.
        /// </summary>
        public static string Activity_DeleteCredential_Property_DeleteCredentialDescription_Description {
            get {
                return ResourceManager.GetString("Activity_DeleteCredential_Property_DeleteCredentialDescription_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Credentials.
        /// </summary>
        public static string Activity_DeleteCredential_Property_DeleteCredentialDisplayName_Name {
            get {
                return ResourceManager.GetString("Activity_DeleteCredential_Property_DeleteCredentialDisplayName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential Type.
        /// </summary>
        public static string Activity_GetCredential_Property_CredentialType_Description {
            get {
                return ResourceManager.GetString("Activity_GetCredential_Property_CredentialType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential Type.
        /// </summary>
        public static string Activity_GetCredential_Property_CredentialType_Name {
            get {
                return ResourceManager.GetString("Activity_GetCredential_Property_CredentialType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential Type.
        /// </summary>
        public static string Activity_GetSecureCredential_Property_CredentialType_Description {
            get {
                return ResourceManager.GetString("Activity_GetSecureCredential_Property_CredentialType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential Type.
        /// </summary>
        public static string Activity_GetSecureCredential_Property_CredentialType_Name {
            get {
                return ResourceManager.GetString("Activity_GetSecureCredential_Property_CredentialType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Secure Credentials.
        /// </summary>
        public static string Activity_GetSecureCredential_Property_GetSecureCredentialDescription_Description {
            get {
                return ResourceManager.GetString("Activity_GetSecureCredential_Property_GetSecureCredentialDescription_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Secure Credentials.
        /// </summary>
        public static string Activity_GetSecureCredential_Property_GetSecureCredentialDisplayName_Name {
            get {
                return ResourceManager.GetString("Activity_GetSecureCredential_Property_GetSecureCredentialDisplayName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Credentials.
        /// </summary>
        public static string Activity_RequestCredential_Property_RequestCredentialDescription_Description {
            get {
                return ResourceManager.GetString("Activity_RequestCredential_Property_RequestCredentialDescription_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Credentials.
        /// </summary>
        public static string Activity_RequestCredential_Property_RequestCredentialDisplayName_Name {
            get {
                return ResourceManager.GetString("Activity_RequestCredential_Property_RequestCredentialDisplayName_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials.
        /// </summary>
        public static string CategoryCredentials {
            get {
                return ResourceManager.GetString("CategoryCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string CategorySystem {
            get {
                return ResourceManager.GetString("CategorySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string MessageDescription {
            get {
                return ResourceManager.GetString("MessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string MessageDisplayName {
            get {
                return ResourceManager.GetString("MessageDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string OutputDisplayName {
            get {
                return ResourceManager.GetString("OutputDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and the secure string password cannot be both not null.
        /// </summary>
        public static string PasswordAndSecureStringNotNull {
            get {
                return ResourceManager.GetString("PasswordAndSecureStringNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and the secure string password cannot be both null.
        /// </summary>
        public static string PasswordAndSecureStringNull {
            get {
                return ResourceManager.GetString("PasswordAndSecureStringNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordDescription {
            get {
                return ResourceManager.GetString("PasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordDisplayName {
            get {
                return ResourceManager.GetString("PasswordDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure String Password.
        /// </summary>
        public static string PasswordSecureStringDescription {
            get {
                return ResourceManager.GetString("PasswordSecureStringDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure String Password .
        /// </summary>
        public static string PasswordSecureStringDisplayName {
            get {
                return ResourceManager.GetString("PasswordSecureStringDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persistance Type .
        /// </summary>
        public static string PersistanceTypeDescription {
            get {
                return ResourceManager.GetString("PersistanceTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersistanceType.
        /// </summary>
        public static string PersistanceTypeDisplayName {
            get {
                return ResourceManager.GetString("PersistanceTypeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string TargetDescription {
            get {
                return ResourceManager.GetString("TargetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string TargetDisplayName {
            get {
                return ResourceManager.GetString("TargetDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TitleDescription {
            get {
                return ResourceManager.GetString("TitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TitleDisplayName {
            get {
                return ResourceManager.GetString("TitleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UsernameDescription {
            get {
                return ResourceManager.GetString("UsernameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UsernameDisplayName {
            get {
                return ResourceManager.GetString("UsernameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The only allowed values for Credential Type are &apos;Generic&apos; or &apos;DomainPassword&apos;.
        /// </summary>
        public static string ValidationError_InvalidCredentialType {
            get {
                return ResourceManager.GetString("ValidationError_InvalidCredentialType", resourceCulture);
            }
        }
    }
}
