version: "3.9"
services:
  test_mssql_windows:
    image: codedwfdemoregistry.azurecr.io/mssql_server:1.0.2
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: 'Y'
      sa_password: 'Sample123$$'

  test_mssql_linux:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'Sample123$$'

  robot:
    image: robotdevregistry.azurecr.io/robot/uiautomation-runtime:23.10.81.43986-robot24.4.0-s137
    volumes:
      - ./mount/input:/input
      - ${MOUNT_OUTPUT}:/output
      - ./mount/application/EnableOfflineExecution.txt:/application/EnableOfflineExecution.txt
      - ./mount/application/NuGet.config:/application/NuGet.config
    environment:
      OFFLINE: 'true'
      LICENSE_AGREEMENT: 'accept'
      SQL_SERVER_HOST: test_mssql_linux
    entrypoint: "/bin/sh /input/startup.sh"
