parameters:
  BuildProject: ""
  BuildConfiguration: "Release"
  BuildPlatform: "Any CPU"
  NuGetVersionSpec: "4.3.0"
  NuGetConfigPath: "$(Build.SourcesDirectory)/Activities/.nuget/NuGet.Config"
  Dependencies: []
  restoreDependencies: []
  rootPath: $(Build.SourcesDirectory)
  packagesDirectory: ""

steps:
- ${{ each depend in parameters.restoreDependencies }}:
  - task: NuGetCommand@2
    displayName: "Restore Nuget packages ${{ depend }}"
    inputs:
      restoreSolution:    ${{ format('{0}{1}', parameters.rootPath, depend) }}
      feedsToUse:         "config"
      nugetConfigPath:    ${{ parameters.NuGetConfigPath }}
      packagesdirectory:  ${{ parameters.packagesDirectory }}

- task: NuGetCommand@2
  displayName: "Restore Nuget packages ${{ parameters.BuildProject }}"
  inputs:
    restoreSolution:    ${{ format('{0}{1}', parameters.rootPath, parameters.BuildProject) }}
    feedsToUse:         "config"
    nugetConfigPath:    ${{ parameters.NuGetConfigPath }}
    packagesdirectory:  ${{ parameters.packagesDirectory }}

- task: VSBuild@1
  displayName: "Build Solution ${{ parameters.BuildProject }}"
  inputs:
    solution:       ${{ format('{0}{1}', parameters.rootPath, parameters.BuildProject) }}
    platform:       ${{ parameters.BuildPlatform }}
    configuration:  ${{ parameters.BuildConfiguration }}
