<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="Current">
  <PropertyGroup>
    <TargetFrameworks>$(PortableFramework);$(WindowsFramework)</TargetFrameworks>
    <OutputPath>..\..\Output\Activities\FTP\</OutputPath>
  </PropertyGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == '$(PortableFramework)' ">
    <PackageReference Include="UiPath.Workflow" />
  </ItemGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == '$(WindowsFramework)' ">
    <PackageReference Include="System.Activities.Core.Presentation" />
    <PackageReference Include="UiPath.Workflow" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentFTP" />
    <PackageReference Include="SSH.NET" />
  </ItemGroup>

</Project>