<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="Current">
  <PropertyGroup>
    <TargetFrameworks>$(PortableFramework);$(WindowsFramework)</TargetFrameworks>
    <OutputPath>..\..\Output\Activities\FTP\</OutputPath>
  </PropertyGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == '$(WindowsFramework)' ">
    <PackageReference Include="System.Activities.Core.Presentation" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentFTP" />
    <PackageReference Include="SSH.NET" />
    <PackageReference Include="UiPath.Workflow" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="UiPath.FTP.Tests" />
    <EmbeddedResource Update="Properties\UiPath.FTP.*.resx">
      <DependentUpon>UiPath.FTP.resx</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

</Project>