<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\Java.build.props" />

  <PropertyGroup>
    <TargetFrameworks>$(PortableFramework);$(WindowsFramework)</TargetFrameworks>
    <OutputPath>..\..\OutputTests\Java\</OutputPath>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="UiPath.Activities.Api" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UiPath.Java.Activities.API\UiPath.Java.Activities.API.csproj" />
    <ProjectReference Include="..\UiPath.Java\UiPath.Java.csproj" />
  </ItemGroup>

</Project>
