<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="Current">
  <Import Project="../Java.build.props" />
  <PropertyGroup>
    <TargetFrameworks>$(PortableFramework)</TargetFrameworks>
    <OutputPath>..\..\Output\Activities\Java\</OutputPath>
  </PropertyGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == '$(PortableFramework)' ">
    <PackageReference Include="UiPath.Workflow" />
  </ItemGroup>
</Project>