<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="Current">
  <Import Project="../Java.build.props" />
  <PropertyGroup>
    <TargetFrameworks>net6.0</TargetFrameworks>
    <OutputPath>..\..\Output\Activities\Java\</OutputPath>
  </PropertyGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == 'net6.0' ">
    <PackageReference Include="UiPath.Workflow" />
  </ItemGroup>
</Project>