<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="Current">
  <Import Project="../Java.build.props" />
  <PropertyGroup>
    <TargetFrameworks>$(PortableFramework)</TargetFrameworks>
    <OutputPath>..\..\Output\Activities\Java\</OutputPath>
  </PropertyGroup>
  <ItemGroup Condition=" '$(TargetFramework)' == '$(PortableFramework)' ">
    <PackageReference Include="UiPath.Workflow" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\UiPath.Java.*.resx">
      <DependentUpon>UiPath.Java.resx</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>
</Project>