<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\Java.build.props" />
	<PropertyGroup>
		<TargetFrameworks>$(PortableFramework);$(WindowsFramework)</TargetFrameworks>
		<OutputPath>$(ProjectDir)..\..\Output\Activities\Java\</OutputPath>
		<VersionSuffix></VersionSuffix>
		<!--leave empty for ci to replace with prelease tag-->
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>UiPath.Java.Activities</PackageId>
		<PackageTitle>UiPath.Java.Activities</PackageTitle>
		<PackageIconUrl>https://download.uipath.com/UI_icon.png?web</PackageIconUrl>
		<PackageLicenseUrl>https://docs.uipath.com/activities/docs/about-the-java-activities-pack</PackageLicenseUrl>
		<PackageTags>UiPathActivities</PackageTags>
		<Description>UiPath Java Activities Pack</Description>
		<Authors>UiPath</Authors>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);AddDlls</TargetsForTfmSpecificBuildOutput>
		<RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.Activities.ViewModels" />
		<PackageReference Include="UiPath.Platform" />
		<PackageReference Include="UiPath.Telemetry.Client" />
		<PackageReference Include="UiPath.CodedWorkflows" />
	</ItemGroup>

	<Target Name="RemoveMetaDll" AfterTargets="BuiltProjectOutputGroup">
		<ItemGroup>
			<BuiltProjectOutputGroupOutput Remove="@(BuiltProjectOutputGroupOutput)" />
		</ItemGroup>
	</Target>

	<ItemGroup>
		<None Include="..\Invoke\artifacts\InvokeJava.jar" Pack="true" PackagePath="lib\java_files\InvokeJava.jar" />
		<None Include="..\Invoke\artifacts\InvokeJavaLinux.jar" Pack="true" PackagePath="lib\java_files\InvokeJavaLinux.jar" />
	</ItemGroup>

	<Target Name="AddDlls">
		<ItemGroup>
			<BuildOutputInPackage Include="$(OutputPath)UiPath.Java.dll" />
			<BuildOutputInPackage Include="$(OutputPath)UiPath.Java.Activities.dll" />

			<JavaActivitiesResources Include="$(OutputPath)**\UiPath.Java.Activities.resources.dll" />
			<BuildOutputInPackage Include="@(JavaActivitiesResources)">
				<TargetPath>%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
			</BuildOutputInPackage>
		</ItemGroup>
		<ItemGroup Condition=" '$(TargetFramework)' != '$(PortableFramework)' ">
			<BuildOutputInPackage Include="$(OutputPath)UiPath.Java.Activities.Design.dll" />

			<JavaActivitiesDesignResources Include="$(OutputPath)**\UiPath.Java.Activities.Design.resources.dll" />
			<BuildOutputInPackage Include="@(JavaActivitiesDesignResources)">
				<TargetPath>%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
			</BuildOutputInPackage>
		</ItemGroup>

		<ItemGroup>
			<BuildOutputInPackage Include="$(OutputPath)UiPath.Java.Activities.ViewModels.dll" />
		</ItemGroup>

    <!--Coded workflow API files-->
    <ItemGroup Label="AddCodedWorkflowAPI">
      <BuildOutputInPackage Include="$(OutputPath)UiPath.Java.Activities.API.dll" />
      <BuildOutputInPackage Include="$(OutputPath)UiPath.Java.Activities.API.xml" />
    </ItemGroup>
	</Target>

	<ItemGroup Condition=" '$(TargetFramework)' != '$(PortableFramework)' ">
		<ProjectReference Include="..\..\Java\UiPath.Java.Activities.Design\UiPath.Java.Activities.Design.csproj">
			<PrivateAssets>All</PrivateAssets>
		</ProjectReference>
	</ItemGroup>
	<ItemGroup Condition=" '$(TargetFramework)' == '$(PortableFramework)' ">
		<ProjectReference Include="..\..\Java\UiPath.Java.Activities\UiPath.Java.Activities.csproj">
			<PrivateAssets>All</PrivateAssets>
		</ProjectReference>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\Java\UiPath.Java.Activities.ViewModels\UiPath.Java.Activities.ViewModels.csproj">
			<PrivateAssets>All</PrivateAssets>
		</ProjectReference>
    <ProjectReference Include="..\..\Java\UiPath.Java.Activities.API\UiPath.Java.Activities.API.csproj">
      <PrivateAssets>All</PrivateAssets>
    </ProjectReference>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition=" '$(TargetFramework)' == '$(PortableFramework)' AND $(ConfigurationName) == Debug ">
		<Exec Command="if exist &quot;$(ProjectDir)..\..\Output\Activities\Packages\UiPath.Java.*&quot; del &quot;$(ProjectDir)..\..\Output\Activities\Packages\UiPath.Java.*&quot;&#xD;&#xA;&#xD;&#xA;&quot;powershell.exe&quot; -file &quot;$(ProjectDir)..\..\Tools\net.sdk\pack-project.ps1&quot; -projectPath &quot;$(ProjectPath)&quot; -outputPath &quot;$(ProjectDir)..\..\Output\Activities\Packages&quot; -suffix &quot;dev&quot;" />
	</Target>
</Project>