trigger:
  batch: true
  branches:
    include:
    - develop
    - masters/Python
    - release/Python/*
    - support/Python/*
  paths:
    include:
    - Activities/Python/*
    - Activities/Activities.Python.sln
    - Activities/Directory.build.targets
    - Activities/Shared/*
    - Activities/Tools/*

pr:
  branches:
    include:
    - develop
    - masters/Python
    - release/Python/*
    - support/Python/*
  paths:
    include:
    - Activities/Python/*
    - Activities/Activities.Python.sln
    - Activities/Directory.build.targets
    - Activities/Shared/*
    - Activities/Tools/*

variables:
  - template: ..\.pipelines\variables\variables.yml

stages:
  - template: ..\.pipelines\templates\stage.start.yml
    parameters:
      projectName: 'Python'
      solutionPath: '$(SolutionsPath)/Activities.Python.sln'
      sonarKeyPrefix: 'CommunityActivities'
      sdkBuild: false
      enableCDStages: false
      hasQaPackages: false
      preTestRun:
      - task: UseDotNet@2
        displayName: 'Install .NET 6 SDK'
        inputs:
          packageType: 'sdk'
          version: '6.0.x'

  - stage: BuildPythonRuntimeTests
    displayName: 'Build Python Runtime Tests'
    dependsOn:
      - Build
    jobs:
    - template: ../.pipelines/jobs/stage.build.runtime.tests.yml
      parameters:
        robotVersion: $(TestsStudioVersion)
        studioProjectPath: 'Activities/Python/UiPath.Python.RuntimeTests/project.json'
        buildForWindows: true
        buildForPortable: false
        packageUnderTestName: 'UiPath.Python.Activities'
        studioLicense: $(StudioLicense)        

  - stage: RunPythonRuntimeTestsWindows
    displayName: 'Run Python Runtime Tests Windows'
    dependsOn:
      - BuildPythonRuntimeTests
    jobs:
    - template: ../.pipelines/jobs/stage.run.runtime.tests.windows.yml
      parameters:
        robotVersion: $(TestsStudioVersion)
        studioLicense: $(StudioLicense)
        environment:
          PYTHON_HOME: $(USEPYTHONVERSION_PYTHONLOCATION)
        beforeTestsCustomSteps:
          - task: UsePythonVersion@0
            displayName: 'Use Python 3.x'

