<Project>
    <!-- Import first the parent targets -->
    <Import Project="../Directory.build.props" />
    
    <PropertyGroup>
        <Product>Python</Product>
        <Description>UiPath Python Activities Pack</Description>
        <Authors>UiPath</Authors>
        <Company>UiPath</Company>
        <Copyright>© UiPath</Copyright>
        <VersionBuild>$([System.DateTime]::UtcNow.ToString("yy"))$([System.DateTime]::UtcNow.DayOfYear.ToString("F0"))</VersionBuild>
        <VersionRevision>$([System.DateTime]::UtcNow.TimeOfDay.TotalMinutes.ToString("F0"))</VersionRevision>
        <VersionPrefix Condition="'$(Configuration)' == 'Release'">2.3.0</VersionPrefix>
        <VersionPrefix Condition="'$(Configuration)' == 'Debug'">2.3.$(VersionBuild)-dev.$(VersionRevision)</VersionPrefix>
        <AssemblyVersion Condition="'$(Configuration)' == 'Debug' and '$(VersionPrefix)' != '' ">2.3.$(VersionBuild).$(VersionRevision)</AssemblyVersion>
        <!--leave empty for ci to replace with pre-release tag-->
        <SolutionDir>$(MSBuildThisFileDirectory)</SolutionDir>
		<DefineConstants>$(DefineConstants);ENABLE_DEFAULT_TELEMETRY</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(IsTestProject)' != 'true'">
        <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <IsConfigurationRelease>true</IsConfigurationRelease>
    </PropertyGroup>
</Project>