//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiPath.Database.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiPath_Database_Activities {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiPath_Database_Activities() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiPath.Database.Activities.Properties.UiPath.Database.Activities", typeof(UiPath_Database_Activities).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AffectedRecords.
        /// </summary>
        public static string AffectedRecordsDisplayName {
            get {
                return ResourceManager.GetString("AffectedRecordsDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColumnNames.
        /// </summary>
        public static string ColumnNamesDisplayName {
            get {
                return ResourceManager.GetString("ColumnNamesDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandType.
        /// </summary>
        public static string CommandTypeDisplayName {
            get {
                return ResourceManager.GetString("CommandTypeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection.
        /// </summary>
        public static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Configuration.
        /// </summary>
        public static string ConnectionConfiguration {
            get {
                return ResourceManager.GetString("ConnectionConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either ConnectionString or ConnectionSecureString must be set!.
        /// </summary>
        public static string ConnectionMustBeSet {
            get {
                return ResourceManager.GetString("ConnectionMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecureConnectionString.
        /// </summary>
        public static string ConnectionSecureStringDisplayName {
            get {
                return ResourceManager.GetString("ConnectionSecureStringDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionString.
        /// </summary>
        public static string ConnectionStringDisplayName {
            get {
                return ResourceManager.GetString("ConnectionStringDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueOnError.
        /// </summary>
        public static string ContinueOnErrorDisplayName {
            get {
                return ResourceManager.GetString("ContinueOnErrorDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatabaseConnection.
        /// </summary>
        public static string DatabaseConnectionDisplayName {
            get {
                return ResourceManager.GetString("DatabaseConnectionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataTable.
        /// </summary>
        public static string DataTableDisplayName {
            get {
                return ResourceManager.GetString("DataTableDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Connection.
        /// </summary>
        public static string ExistingDbConnectionDisplayName {
            get {
                return ResourceManager.GetString("ExistingDbConnectionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string OutputDisplayName {
            get {
                return ResourceManager.GetString("OutputDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string ParametersDisplayName {
            get {
                return ResourceManager.GetString("ParametersDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProviderName.
        /// </summary>
        public static string ProviderNameDisplayName {
            get {
                return ResourceManager.GetString("ProviderNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableName.
        /// </summary>
        public static string TableNameDisplayName {
            get {
                return ResourceManager.GetString("TableNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (milliseconds).
        /// </summary>
        public static string TimeoutMSDisplayName {
            get {
                return ResourceManager.GetString("TimeoutMSDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value provided for TimeoutMS must be &gt;= 0.
        /// </summary>
        public static string TimeoutMSException {
            get {
                return ResourceManager.GetString("TimeoutMSException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseTransaction.
        /// </summary>
        public static string UseTransactionDisplayName {
            get {
                return ResourceManager.GetString("UseTransactionDisplayName", resourceCulture);
            }
        }
    }
}
