trigger:
  batch: true
  branches:
    include:
    - develop
    - masters/Database
    - release/Database/*
    - support/Database/*
  paths:
    include:
    - Activities/Database/*
    - Activities/Activities.Database.sln
    - Activities/Directory.build.targets
    - Activities/Shared/*
    - Activities/Tools/*

pr:
  branches:
    include:
    - develop
    - masters/Database
    - release/Database/*
    - support/Database/*
  paths:
    include:
    - Activities/Database/*
    - Activities/Activities.Database.sln
    - Activities/Directory.build.targets
    - Activities/Shared/*
    - Activities/Tools/*

variables:
  - template: ..\.pipelines\variables\variables.yml
  - name: PerformDatabaseTests
    value: false

stages:
  - template: ..\.pipelines\templates\stage.start.yml
    parameters:
      projectName: 'Database'
      solutionPath: '$(SolutionsPath)/Activities.Database.sln'
      sdkBuild: false
      enableCDStages: false
      hasQaPackages: false
      preTestRun:
      - task: UseDotNet@2
        displayName: 'Install .NET 6 SDK'
        inputs:
          packageType: 'sdk'
          version: '6.0.x'

  - stage: CreateAndSetupBYOSAgent
    dependsOn:
      - Build
    condition: eq(variables.PerformDatabaseTests, true)
    displayName: "Create and Setup BYOS Agent"
    variables:
      eteKvName: "ete-variables-kv"
      athenaservicesAgentPrefix: "cact"
      eteAgentPoolName: vcanja1
      eteProjName: "Ephemeral Testing Environment"
    jobs:
    - template: "stage.create.byos.agent.yml"

  - stage: BuildDatabaseRuntimeTests
    displayName: 'Build Database Runtime Tests'
    dependsOn:
      - CreateAndSetupBYOSAgent
    condition: eq(variables.PerformDatabaseTests, true)
    jobs:
    - template: ../.pipelines/jobs/stage.build.runtime.tests.yml
      parameters:
        robotVersion: $(TestsStudioVersion)
        studioProjectPath: 'Activities/Database/UiPath.Database.Runtime.Tests/project.json'
        buildForWindows: true
        buildForPortable: true
        packageUnderTestName: 'UiPath.Database.Activities'
        studioLicense: $(StudioLicense)

  - stage: RunDatabaseRuntimeTestsWindows
    displayName: 'Run Database Runtime Tests Windows'
    variables:
      DatabaseServicesAgentPublicIp: $[stageDependencies.CreateAndSetupBYOSAgent.ConfigureDatabaseServicesAgents.outputs['AddNsgRule.DatabaseServicesAgentPublicIp']]
    dependsOn:
      - BuildDatabaseRuntimeTests
      - CreateAndSetupBYOSAgent
    condition: eq(variables.PerformDatabaseTests, true)      
    jobs:
    - template: ../.pipelines/jobs/stage.run.runtime.tests.windows.yml
      parameters:
        robotVersion: $(TestsStudioVersion)
        studioLicense: $(StudioLicense)
        environment:
          SQL_SERVER_HOST: "$(DatabaseServicesAgentPublicIp)"

  - stage: RunDatabaseRuntimeTestsPortable
    displayName: 'Run Database Runtime Tests Portable'
    variables:
      DatabaseServicesAgentPublicIp: $[stageDependencies.CreateAndSetupBYOSAgent.ConfigureDatabaseServicesAgents.outputs['AddNsgRule.DatabaseServicesAgentPublicIp']]
    dependsOn:
      - BuildDatabaseRuntimeTests
      - CreateAndSetupBYOSAgent
    condition: eq(variables.PerformDatabaseTests, true)
    jobs:
    - template: ../.pipelines/jobs/stage.run.runtime.tests.portable.yml
      parameters:
        robotVersion: $(TestsStudioVersion)
        environment:
          SQL_SERVER_HOST: "$(DatabaseServicesAgentPublicIp)"

  - stage: DeleteBYOSAgent
    displayName: "Delete BYOS Agent"
    condition: eq(variables.PerformDatabaseTests, true)
    variables:
      athenaservicesEnvironmentIds: $[stageDependencies.CreateAndSetupBYOSAgent.CreateBYOSAgent.outputs['DeployDatabaseServicesImage.environmentIds']]
      eteKvName: "ete-variables-kv"
    dependsOn:
      - CreateAndSetupBYOSAgent
      - RunDatabaseRuntimeTestsPortable
      - RunDatabaseRuntimeTestsWindows
    jobs:
    - template: stage.delete.byos.agent.yml