<Project>
    <!-- Import first the parent targets -->
    <Import Project="../Directory.build.targets" />

    <ItemGroup>
        <!-- When upgrading Microsoft.Data.SqlClient please upgrade also the native SNI dll-->
        <PackageReference Update="Microsoft.Data.SqlClient" Version="5.2.1" />
        <PackageReference Update="System.Data.Common" Version="4.3.0" />
        <PackageReference Update="System.Data.Odbc" Version="8.0.0" />
        <PackageReference Update="System.Data.OleDb" Version="8.0.0" />
        <PackageReference Update="Oracle.ManagedDataAccess.Core" Version="23.8.0"/>
        <PackageReference Update="System.Resources.Extensions" Version="8.0.0" />
		<PackageReference Update="System.Activities.Presentation" Version="6.0.0-20250327.10" />
		
		<!-- Studio contract-->
		<PackageReference Update="UiPath.Activities.Contracts" Version="24.10.1" PrivateAssets="All" />
		<PackageReference Update="UiPath.Activities.Api" Version="24.10.1" PrivateAssets="All" />
		<PackageReference Update="UiPath.Platform" PrivateAssets="All" />
    </ItemGroup>
    
</Project>