parameters:
  robotVersion: '24.2.1-beta.15932'

jobs:
- job: "RunDatabaseRuntimeTestsPortable"
  displayName: "Run Database Runtime Tests Portable"
  variables:
    IntegrationTestStudioPackPath: '$(System.ArtifactsDirectory)/Packages'
    StudioProjectPath: 'Activities/Database/UiPath.Database.Runtime.Tests/project.json'
  timeoutInMinutes: 90
  pool:
    vmImage: ubuntu-latest
  workspace:
    clean: outputs | resources | all

  steps:
  - task: UniversalPackages@0
    displayName: "Download TestRunner"
    inputs:
      command: 'download'
      downloadDirectory: "$(Build.ArtifactStagingDirectory)/TestRunner"
      vstsFeed: "UiPath-DevPackages"
      vstsFeedPackage: "uipath.testrunner"
      vstsPackageVersion: "1.587.4306"
      verbosity: 'Trace'

  - task: Docker@2
    displayName: Login to container registry
    inputs:
      command: login
      containerRegistry: 'robotdevregistry'

  - bash: |
      cd $(Build.SourcesDirectory)/Activities/Database/UiPath.Database.Runtime.Tests/docker
      docker-compose --version
      export MOUNT_OUTPUT=$(System.ArtifactsDirectory)
      chmod -R 777 $(System.ArtifactsDirectory)
      docker-compose up -d test_mssql_linux
      docker-compose up -d robot
    displayName: "Start containers"

  - task: DownloadPipelineArtifact@2
    displayName: "Download Packages"
    inputs:
      artifact: "Packages"
      path: "$(IntegrationTestStudioPackPath)"

  - bash: |
      docker ps
      cp -rvf $(Build.ArtifactStagingDirectory)/TestRunner $(Build.SourcesDirectory)/Activities/Database/UiPath.Database.Runtime.Tests/docker/mount/input/
      cp -vf $(IntegrationTestStudioPackPath)/UiPath.Database.Runtime.Tests_portable* $(Build.SourcesDirectory)/Activities/Database/UiPath.Database.Runtime.Tests/docker/mount/input/
      PACKAGE=$(basename $(ls $(Build.SourcesDirectory)/Activities/Database/UiPath.Database.Runtime.Tests/docker/mount/input/*_portable*.nupkg))
      echo "package = $PACKAGE"
      echo "##vso[task.setvariable variable=pkgPath]/input/$PACKAGE"
    displayName: 'Prepare tests'

  - bash: |
      cd $(Build.SourcesDirectory)/Activities/Database/UiPath.Database.Runtime.Tests/docker
      export MOUNT_OUTPUT=$(System.ArtifactsDirectory)
      export SQL_SERVER_HOST="test_mssql_linux"
      chmod -R 777  $(System.ArtifactsDirectory)
      docker-compose exec -T robot dotnet /input/TestRunner/uipath.studio.codedwf.tests.runner.dll run --package $(pkgPath) --robotPath /application/UiRobot.dll --output /output
    displayName: 'Run tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testRunTitle: "Portable Runtime Tests"
      testResultsFiles: '$(System.ArtifactsDirectory)/results*.trx'
      publishRunAttachments: true
      failTaskOnFailedTests: true
      mergeTestResults: true
    displayName: 'Publish Tests Results'
    condition: always()    