parameters:
  robotVersion: '24.2.1-beta.15932'

jobs:
- job: "RunDatabaseRuntimeTestsWindows"
  displayName: "Run Database Runtime Tests Windows"
  variables:
    IntegrationTestStudioPackPath: '$(System.ArtifactsDirectory)/Packages'
    StudioProjectPath: 'Activities/Database/UiPath.Database.Runtime.Tests/project.json'
  timeoutInMinutes: 90
  pool:
    vmImage: windows-2022
  workspace:
    clean: outputs | resources | all

  steps:
  - task: UniversalPackages@0
    displayName: "Download TestRunner"
    inputs:
      command: 'download'
      downloadDirectory: "$(Build.ArtifactStagingDirectory)/TestRunner"
      vstsFeed: "UiPath-DevPackages"
      vstsFeedPackage: "uipath.testrunner"
      vstsPackageVersion: "1.587.4306"
      verbosity: 'Trace'

  - task: BuildProcessCleaner@0
     
  - task: ms-autotest.screen-resolution-utility-task.screen-resolution-utlity-task.ScreenResolutionUtility@1
    displayName: 'Set Screen Resolution'
    inputs:
      displaySettings: specific
      width: 1920
      height: 1080

  - task: Docker@2
    displayName: Login to container registry
    inputs:
      command: login
      containerRegistry: 'codedwfdemoregistry'

  - task: UseDotNet@2
    displayName: 'Use .NET SDK 8.0.x'
    inputs:
      packageType: 'sdk'
      version: '8.0.x'

  - task: DownloadPipelineArtifact@2
    displayName: "Download Packages"
    inputs:
      artifact: "Packages"
      path: "$(IntegrationTestStudioPackPath)"

  # install robot
  - template: Testing/Automation/install.studio.steps.template.yml@automationTests
    parameters:
      installType: 'machine'
      studioVersion: ${{ parameters.robotVersion }}
      license: "7445-1270-1408-6250"
      studioCustomNugetFeeds: 'UiPath-Internal,https://uipath.pkgs.visualstudio.com/Public.Feeds/_packaging/UiPath-Internal/nuget/v3/index.json'

  - powershell: |
      & "C:/Program Files/UiPath/Studio/UiRobot.exe" trace --enableLowLevel
    displayName: "Enable robot low level"
    failOnStderr: false
  
  - task: DockerCompose@0
    inputs:
      dockerComposeFile: '$(Build.SourcesDirectory)/Activities/Database/UiPath.Database.Runtime.Tests/docker/docker-compose.yml'
      action: 'Run a specific service'
      serviceName: 'test_mssql_windows'
      ports:
        1433:1433
    displayName: 'Run SQL Server Image'

  - powershell: |
      $filepath = Get-ChildItem $(IntegrationTestStudioPackPath)/UiPath.Database.Runtime.Tests_windows*
      $fullPath = $filepath.FullName
      docker ps
      $env:SQL_SERVER_HOST="localhost"
      $(Build.ArtifactStagingDirectory)/TestRunner/uipath.studio.codedwf.tests.runner.exe run --package $fullPath --output $(System.ArtifactsDirectory)
    displayName: 'Execute tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testRunTitle: "Windows Runtime Tests"
      testResultsFiles: '$(System.ArtifactsDirectory)/results*.trx'
      publishRunAttachments: true
      failTaskOnFailedTests: true
      mergeTestResults: true
    displayName: 'Publish Tests Results'
    condition: always()