<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="Current">
  <Import Project="..\Python.build.props" />
  <PropertyGroup>
    <PackageId>.noconflict</PackageId>
    <TargetFrameworks>net6.0</TargetFrameworks>
    <OutputPath>..\..\Output\Activities\Python\</OutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <!--<PropertyGroup>
    <PreBuildEvent>"$(ProjectDir)..\..\Tools\localization_utilities\dist\synchronize_localization.exe" "$(ProjectDir)\" "$(ProjectName)</PreBuildEvent>
  </PropertyGroup>-->
  <Import Project="..\..\Shared\UiPath.Shared.Activities\UiPath.Shared.Activities.projitems" Label="Shared" />
  <Import Project="..\..\Shared\UiPath.Shared\UiPath.Shared.projitems" Label="Shared" />
  <ItemGroup>
    <PackageReference Include="UiPath.Workflow" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\UiPath.Python.Activities.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>UiPath.Python.Activities.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="UiPath.Activities.Api" />
    <PackageReference Include="UiPath.Activities.Contracts" />
    <ProjectReference Include="..\UiPath.Python\UiPath.Python.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\UiPath.Python.Activities.fr.resx">
      <DependentUpon>UiPath.Python.Activities.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\UiPath.Python.Activities.ja.resx">
      <DependentUpon>UiPath.Python.Activities.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\UiPath.Python.Activities.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>UiPath.Python.Activities.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\UiPath.Python.Activities.ru.resx">
      <DependentUpon>UiPath.Python.Activities.resx</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>
</Project>