//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiPath.Java.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UiPath_Java {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiPath_Java() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiPath.Java.Properties.UiPath.Java", typeof(UiPath_Java).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not cast java object to array..
        /// </summary>
        internal static string CastArrayException {
            get {
                return ResourceManager.GetString("CastArrayException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not cast java object to dot net type..
        /// </summary>
        internal static string CastException {
            get {
                return ResourceManager.GetString("CastException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target type was not found..
        /// </summary>
        internal static string ClassNotFoundException {
            get {
                return ResourceManager.GetString("ClassNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor could not be invoked..
        /// </summary>
        internal static string ConstructorNotFoundException {
            get {
                return ResourceManager.GetString("ConstructorNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result from java could not be deserialized..
        /// </summary>
        internal static string DeserializationException {
            get {
                return ResourceManager.GetString("DeserializationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field with the specified name was not found on target..
        /// </summary>
        internal static string FieldNotFoundException {
            get {
                return ResourceManager.GetString("FieldNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only public member can be accessed..
        /// </summary>
        internal static string IllegalAccessException {
            get {
                return ResourceManager.GetString("IllegalAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An illegalal or inapropriate parameter has been passed..
        /// </summary>
        internal static string IllegalArgumentsException {
            get {
                return ResourceManager.GetString("IllegalArgumentsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified instance was not created..
        /// </summary>
        internal static string InstanceNotFoundException {
            get {
                return ResourceManager.GetString("InstanceNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target class could not be instatiated..
        /// </summary>
        internal static string InstantiationException {
            get {
                return ResourceManager.GetString("InstantiationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invocation exception has occured during the execution of the target..
        /// </summary>
        internal static string InvocationTargetException {
            get {
                return ResourceManager.GetString("InvocationTargetException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The jar with specified path was already loaded..
        /// </summary>
        internal static string JarAlreadyLoadedException {
            get {
                return ResourceManager.GetString("JarAlreadyLoadedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the specified jar was not found or does not exist..
        /// </summary>
        internal static string JarNotFoundException {
            get {
                return ResourceManager.GetString("JarNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jar could not be loaded..
        /// </summary>
        internal static string JarNotLoadedException {
            get {
                return ResourceManager.GetString("JarNotLoadedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method could not be invoked..
        /// </summary>
        internal static string MethodNotFoundException {
            get {
                return ResourceManager.GetString("MethodNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not serialize the .net object.
        /// </summary>
        internal static string SerializationException {
            get {
                return ResourceManager.GetString("SerializationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected exception has occurred during the invocation..
        /// </summary>
        internal static string UnknowException {
            get {
                return ResourceManager.GetString("UnknowException", resourceCulture);
            }
        }
    }
}
