//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiPath.ZenDesk.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiPath.ZenDesk.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Authentication과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Common과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If set, continue executing the remaining activities even if the current activity has failed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ContinueOnError과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Single Ticket object 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetTicket_Data_Description {
            get {
                return ResourceManager.GetString("GetTicket_Data_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ticket과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetTicket_Data_DisplayName {
            get {
                return ResourceManager.GetString("GetTicket_Data_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get ticket detail과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetTicket_Description {
            get {
                return ResourceManager.GetString("GetTicket_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GetTicket과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetTicket_DisplayName {
            get {
                return ResourceManager.GetString("GetTicket_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tecket Id과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetTicket_Id_Description {
            get {
                return ResourceManager.GetString("GetTicket_Id_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Id과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetTicket_Id_DisplayName {
            get {
                return ResourceManager.GetString("GetTicket_Id_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status code for request과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetTicket_Status_Description {
            get {
                return ResourceManager.GetString("GetTicket_Status_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetTicket_Status_DisplayName {
            get {
                return ResourceManager.GetString("GetTicket_Status_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get ticket field option with given name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetTicketFieldOption_Description {
            get {
                return ResourceManager.GetString("GetTicketFieldOption_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GetTicketFieldOption과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetTicketFieldOption_DisplayName {
            get {
                return ResourceManager.GetString("GetTicketFieldOption_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   custom field id from ticket과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetTicketFieldOption_Id_Description {
            get {
                return ResourceManager.GetString("GetTicketFieldOption_Id_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Id과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetTicketFieldOption_Id_DisplayName {
            get {
                return ResourceManager.GetString("GetTicketFieldOption_Id_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   matched name value과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetTicketFieldOption_Name_Description {
            get {
                return ResourceManager.GetString("GetTicketFieldOption_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetTicketFieldOption_Name_DisplayName {
            get {
                return ResourceManager.GetString("GetTicketFieldOption_Name_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   matched ticket filed option과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetTicketFieldOption_TicketFieldOption_Description {
            get {
                return ResourceManager.GetString("GetTicketFieldOption_TicketFieldOption_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TicketFieldOption과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetTicketFieldOption_TicketFieldOption_DisplayName {
            get {
                return ResourceManager.GetString("GetTicketFieldOption_TicketFieldOption_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get user detail과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetUser_Description {
            get {
                return ResourceManager.GetString("GetUser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GetUser과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetUser_DisplayName {
            get {
                return ResourceManager.GetString("GetUser_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User id과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetUser_Id_Description {
            get {
                return ResourceManager.GetString("GetUser_Id_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Id과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetUser_Id_DisplayName {
            get {
                return ResourceManager.GetString("GetUser_Id_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User detail info 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetUser_User_Description {
            get {
                return ResourceManager.GetString("GetUser_User_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetUser_User_DisplayName {
            get {
                return ResourceManager.GetString("GetUser_User_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Get user fields data과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetUserFields_Description {
            get {
                return ResourceManager.GetString("GetUserFields_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GetUserFields과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetUserFields_DisplayName {
            get {
                return ResourceManager.GetString("GetUserFields_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All User Fields 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetUserFields_UserFields_Description {
            get {
                return ResourceManager.GetString("GetUserFields_UserFields_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UserFields과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string GetUserFields_UserFields_DisplayName {
            get {
                return ResourceManager.GetString("GetUserFields_UserFields_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute).과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeout (milliseconds)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The activity timed out and was canceled.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ticket will be update 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateTicket_Body_Description {
            get {
                return ResourceManager.GetString("UpdateTicket_Body_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ticket 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateTicket_Body_DisplayName {
            get {
                return ResourceManager.GetString("UpdateTicket_Body_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update ticket detail과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateTicket_Description {
            get {
                return ResourceManager.GetString("UpdateTicket_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UpdateTicket과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateTicket_DisplayName {
            get {
                return ResourceManager.GetString("UpdateTicket_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ticket id과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateTicket_Id_Description {
            get {
                return ResourceManager.GetString("UpdateTicket_Id_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Id과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateTicket_Id_DisplayName {
            get {
                return ResourceManager.GetString("UpdateTicket_Id_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update result message과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateTicket_Message_Description {
            get {
                return ResourceManager.GetString("UpdateTicket_Message_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Message과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateTicket_Message_DisplayName {
            get {
                return ResourceManager.GetString("UpdateTicket_Message_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status code for request과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateTicket_Status_Description {
            get {
                return ResourceManager.GetString("UpdateTicket_Status_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string UpdateTicket_Status_DisplayName {
            get {
                return ResourceManager.GetString("UpdateTicket_Status_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide a value either for {0} or {1}, but not both.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide values for both {0} and {1}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot be used outside of a {0}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide a value for {0}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API Token for authentication과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ZendeskScope_APIToken_Description {
            get {
                return ResourceManager.GetString("ZendeskScope_APIToken_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   APIToken과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ZendeskScope_APIToken_DisplayName {
            get {
                return ResourceManager.GetString("ZendeskScope_APIToken_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Zendesk scope container 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ZendeskScope_Description {
            get {
                return ResourceManager.GetString("ZendeskScope_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ZendeskScope과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ZendeskScope_DisplayName {
            get {
                return ResourceManager.GetString("ZendeskScope_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email addresss for authentication과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ZendeskScope_Email_Description {
            get {
                return ResourceManager.GetString("ZendeskScope_Email_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ZendeskScope_Email_DisplayName {
            get {
                return ResourceManager.GetString("ZendeskScope_Email_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subdomain for zendesk과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ZendeskScope_Subdomain_Description {
            get {
                return ResourceManager.GetString("ZendeskScope_Subdomain_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Subdomain과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ZendeskScope_Subdomain_DisplayName {
            get {
                return ResourceManager.GetString("ZendeskScope_Subdomain_DisplayName", resourceCulture);
            }
        }
    }
}
