//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiPath.Cryptography.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UiPath_Cryptography {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiPath_Cryptography() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiPath.Cryptography.Properties.UiPath.Cryptography", typeof(UiPath_Cryptography).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AES (Deprecated).
        /// </summary>
        internal static string AES {
            get {
                return ResourceManager.GetString("AES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AES GCM.
        /// </summary>
        internal static string AESGCM {
            get {
                return ResourceManager.GetString("AESGCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DES  (Deprecated).
        /// </summary>
        internal static string DES {
            get {
                return ResourceManager.GetString("DES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle to File input.
        /// </summary>
        internal static string General_FileInput {
            get {
                return ResourceManager.GetString("General_FileInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle to File Path input.
        /// </summary>
        internal static string General_FilePathInput {
            get {
                return ResourceManager.GetString("General_FilePathInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HMACMD5 (Non-FIPS).
        /// </summary>
        internal static string HMACMD5 {
            get {
                return ResourceManager.GetString("HMACMD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HMACRIPEMD160 (Non-FIPS).
        /// </summary>
        internal static string HMACRIPEMD160 {
            get {
                return ResourceManager.GetString("HMACRIPEMD160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HMACSHA1.
        /// </summary>
        internal static string HMACSHA1 {
            get {
                return ResourceManager.GetString("HMACSHA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HMACSHA256.
        /// </summary>
        internal static string HMACSHA256 {
            get {
                return ResourceManager.GetString("HMACSHA256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HMACSHA384.
        /// </summary>
        internal static string HMACSHA384 {
            get {
                return ResourceManager.GetString("HMACSHA384", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HMACSHA512.
        /// </summary>
        internal static string HMACSHA512 {
            get {
                return ResourceManager.GetString("HMACSHA512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle to text input.
        /// </summary>
        internal static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MACTripleDES.
        /// </summary>
        internal static string MACTripleDES {
            get {
                return ResourceManager.GetString("MACTripleDES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD5 (Non-FIPS).
        /// </summary>
        internal static string MD5 {
            get {
                return ResourceManager.GetString("MD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RC2 (Non-FIPS)  (Deprecated).
        /// </summary>
        internal static string RC2 {
            get {
                return ResourceManager.GetString("RC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rijndael (Non-FIPS)  (Deprecated).
        /// </summary>
        internal static string Rijndael {
            get {
                return ResourceManager.GetString("Rijndael", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIPEMD160 (Non-FIPS).
        /// </summary>
        internal static string RIPEMD160 {
            get {
                return ResourceManager.GetString("RIPEMD160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle to Secure input.
        /// </summary>
        internal static string SecureKey {
            get {
                return ResourceManager.GetString("SecureKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA1.
        /// </summary>
        internal static string SHA1 {
            get {
                return ResourceManager.GetString("SHA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA256.
        /// </summary>
        internal static string SHA256 {
            get {
                return ResourceManager.GetString("SHA256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA384.
        /// </summary>
        internal static string SHA384 {
            get {
                return ResourceManager.GetString("SHA384", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHA512.
        /// </summary>
        internal static string SHA512 {
            get {
                return ResourceManager.GetString("SHA512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TripleDES.
        /// </summary>
        internal static string TripleDES {
            get {
                return ResourceManager.GetString("TripleDES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided hash algorithm is not supported..
        /// </summary>
        internal static string UnsupportedHashAlgorithmException {
            get {
                return ResourceManager.GetString("UnsupportedHashAlgorithmException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided keyed hash algorithm is not supported..
        /// </summary>
        internal static string UnsupportedKeyedHashAlgorithmException {
            get {
                return ResourceManager.GetString("UnsupportedKeyedHashAlgorithmException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided symmetric algorithm is not supported..
        /// </summary>
        internal static string UnsupportedSymmetricAlgorithmException {
            get {
                return ResourceManager.GetString("UnsupportedSymmetricAlgorithmException", resourceCulture);
            }
        }
    }
}
