<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\Python.build.props" />
    <PropertyGroup>
        <TargetFrameworks>$(PortableFramework);$(WindowsFramework)</TargetFrameworks>
        <OutputPath>$(ProjectDir)..\..\Output\Activities\Python\</OutputPath>
        <VersionSuffix></VersionSuffix>
        <!--leave empty for ci to replace with prelease tag-->
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>UiPath.Python.Activities</PackageId>
        <PackageTitle>UiPath.Python.Activities</PackageTitle>
        <PackageIconUrl>https://download.uipath.com/UI_icon.png?web</PackageIconUrl>
        <PackageLicenseUrl>https://docs.uipath.com/activities/docs/about-the-python-activities-pack</PackageLicenseUrl>
        <PackageTags>UiPathActivities</PackageTags>
        <Description>UiPath Python Activities Pack</Description>
        <Authors>UiPath</Authors>
        <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);AddDlls</TargetsForTfmSpecificBuildOutput>
        <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
    </PropertyGroup>

    <Target Name="RemoveMetaDll" AfterTargets="BuiltProjectOutputGroup">
        <ItemGroup>
            <BuiltProjectOutputGroupOutput Remove="@(BuiltProjectOutputGroupOutput)" />
        </ItemGroup>
    </Target>

    <ItemGroup Label="Reference3rdParties">
        <None Include="..\3rdparty\Python.Runtime*.dll" LinkBase="x86" CopyToOutputDirectory="PreserveNewest" />
        <None Include="..\3rdparty\x64\Python.Runtime*.dll" LinkBase="x64" CopyToOutputDirectory="PreserveNewest" />        
    </ItemGroup>

    <Target Name="AddDlls">
        <ItemGroup Label="AddActivitiesDlls">
            <BuildOutputInPackage Include="$(OutputPath)UiPath.Python.dll" />
            <BuildOutputInPackage Include="$(OutputPath)UiPath.Python.Activities.dll" />
            <BuildOutputInPackage Include="$(OutputPath)UiPath.Python.Activities.ViewModels.dll" />

            <PythonResources Include="$(OutputPath)**\UiPath.Python.resources.dll" />
            <BuildOutputInPackage Include="@(PythonResources)">
                <TargetPath>%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
            </BuildOutputInPackage>

            <PythonActivitiesResources Include="$(OutputPath)**\UiPath.Python.Activities.resources.dll" />
            <BuildOutputInPackage Include="@(PythonActivitiesResources)">
                <TargetPath>%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
            </BuildOutputInPackage>
        </ItemGroup>

        <ItemGroup Label="AddPythonHost">
            <TfmSpecificPackageFile Include="$(OutputPath)*.dll">
                <PackagePath>bin\$(TargetFramework)$(TargetPlatformVersion)</PackagePath>
            </TfmSpecificPackageFile>
            <TfmSpecificPackageFile Include="$(OutputPath)**\Python.Runtime*.dll">
                <PackagePath>bin\$(TargetFramework)$(TargetPlatformVersion)</PackagePath>
            </TfmSpecificPackageFile>
            <TfmSpecificPackageFile Include="$(OutputPath)UiPath.Python.Host*.json">
                <PackagePath>bin\$(TargetFramework)$(TargetPlatformVersion)</PackagePath>
            </TfmSpecificPackageFile>
            <TfmSpecificPackageFile Include="$(OutputPath)**\UiPath.Python.resources.dll">
                <PackagePath>bin\$(TargetFramework)$(TargetPlatformVersion)</PackagePath>
            </TfmSpecificPackageFile>
            
            <TfmSpecificPackageFile Remove="$(OutputPath)UiPath.Python.Activities*.dll" />
            <TfmSpecificPackageFile Remove="$(OutputPath)UiPath.Python.Packaging.dll" />
        </ItemGroup>
    </Target>

    <ItemGroup>
        <ProjectReference Include="..\..\Python\UiPath.Python.Activities.ViewModels\UiPath.Python.Activities.ViewModels.csproj">
            <PrivateAssets>All</PrivateAssets>
        </ProjectReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Python\UiPath.Python.Activities\UiPath.Python.Activities.csproj">
            <PrivateAssets>All</PrivateAssets>
        </ProjectReference>
        <ProjectReference Include="..\..\Python\UiPath.Python.Host32\UiPath.Python.Host32.csproj">
            <PrivateAssets>All</PrivateAssets>
        </ProjectReference>
        <ProjectReference Include="..\..\Python\UiPath.Python.Host\UiPath.Python.Host.csproj">
            <PrivateAssets>All</PrivateAssets>
        </ProjectReference>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="System.Activities.ViewModels" />
    </ItemGroup>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition=" '$(TargetFramework)' == '$(PortableFramework)' AND $(ConfigurationName) == Debug ">
        <Exec Command="if exist &quot;$(ProjectDir)..\..\Output\Activities\Packages\UiPath.Python.*&quot; del &quot;$(ProjectDir)..\..\Output\Activities\Packages\UiPath.Python.*&quot;&#xD;&#xA;&#xD;&#xA;&quot;powershell.exe&quot; -file &quot;$(ProjectDir)..\..\Tools\net.sdk\pack-project.ps1&quot; -projectPath &quot;$(ProjectPath)&quot; -outputPath &quot;$(ProjectDir)..\..\Output\Activities\Packages&quot; -suffix &quot;dev&quot;" />
        
</Target>
</Project>