<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="Current">
    <PropertyGroup>
        <TargetFrameworks>$(PortableFramework)</TargetFrameworks>
        <OutputPath>..\..\Output\Activities\Python\</OutputPath>
    </PropertyGroup>
    <!--<PropertyGroup>
    <PreBuildEvent>"$(ProjectDir)..\..\Tools\localization_utilities\dist\synchronize_localization.exe" "$(ProjectDir)\" "$(ProjectName)</PreBuildEvent>
  </PropertyGroup>-->
    <Import Project="..\..\Shared\UiPath.Shared\UiPath.Shared.projitems" Label="Shared" />
    <Import Project="..\Shared\UiPath.Shared.Service\UiPath.Shared.Service.projitems" Label="Shared" />
    <ItemGroup>
        <PackageReference Include="UiPath.Workflow" />
        <PackageReference Include="pythonnet" />
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Update="Properties\UiPath.Python.*.resx">
            <DependentUpon>UiPath.Python.resx</DependentUpon>
        </EmbeddedResource>
        <EmbeddedResource Update="Properties\UiPath.Python.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>UiPath.Python.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="Scripts\Init.py" />
    </ItemGroup>
    <ItemGroup>
        <Compile Update="Properties\UiPath.Python.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>UiPath.Python.resx</DependentUpon>
        </Compile>
    </ItemGroup>

</Project>