//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiPath.Python.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiPath_Python {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public UiPath_Python() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiPath.Python.Properties.UiPath.Python", typeof(UiPath_Python).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string Activity_PythonScope_Property_Auto_Description {
            get {
                return ResourceManager.GetString("Activity_PythonScope_Property_Auto_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python deserialization exception.
        /// </summary>
        public static string DeserializationException {
            get {
                return ResourceManager.GetString("DeserializationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not detect Python version.
        /// </summary>
        public static string DetectVersionException {
            get {
                return ResourceManager.GetString("DetectVersionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python instantiation exception.
        /// </summary>
        public static string InstantiationException {
            get {
                return ResourceManager.GetString("InstantiationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python exe was not found.
        /// </summary>
        public static string PythonExeNotFoundException {
            get {
                return ResourceManager.GetString("PythonExeNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python runtime type/method/property not found: {0}.
        /// </summary>
        public static string PythonRuntimeTypeException {
            get {
                return ResourceManager.GetString("PythonRuntimeTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python serialization exception.
        /// </summary>
        public static string SerializationException {
            get {
                return ResourceManager.GetString("SerializationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python timeout elapsed.
        /// </summary>
        public static string TimeoutException {
            get {
                return ResourceManager.GetString("TimeoutException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python version {0} is not supported. Supported versions are: {1}.
        /// </summary>
        public static string UnsupportedVersionException {
            get {
                return ResourceManager.GetString("UnsupportedVersionException", resourceCulture);
            }
        }
    }
}
