<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\Credentials.build.props" />
	<PropertyGroup>
		<TargetFrameworks>$(WindowsFramework)</TargetFrameworks>
		<OutputPath>$(ProjectDir)..\..\Output\Activities\Credentials\</OutputPath>
		<VersionSuffix></VersionSuffix>
		<!--leave empty for ci to replace with prelease tag-->
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>UiPath.Credentials.Activities</PackageId>
		<PackageTitle>UiPath.Credentials.Activities</PackageTitle>
		<PackageIconUrl>https://download.uipath.com/UI_icon.png?web</PackageIconUrl>
		<PackageLicenseUrl>https://docs.uipath.com/activities/docs/about-the-credentials-activities-pack</PackageLicenseUrl>
		<PackageTags>UiPathActivities</PackageTags>
		<Description>UiPath Credentials Activities Pack</Description>
		<Authors>UiPath</Authors>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);AddDlls</TargetsForTfmSpecificBuildOutput>
		<RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.Activities.ViewModels" />
    <PackageReference Include="UiPath.Telemetry.Client" />
    <PackageReference Include="UiPath.Platform"/>
    <PackageReference Include="UiPath.CodedWorkflows" />
	</ItemGroup>

	<Target Name="RemoveMetaDll" AfterTargets="BuiltProjectOutputGroup">
		<ItemGroup>
			<BuiltProjectOutputGroupOutput Remove="@(BuiltProjectOutputGroupOutput)" />
		</ItemGroup>
	</Target>

	<Target Name="AddDlls">
		<ItemGroup>
			<BuildOutputInPackage Include="$(OutputPath)UiPath.Credentials.Activities.dll" />
			<CredentialsActivitiesResources Include="$(OutputPath)**\UiPath.Credentials.Activities.resources.dll" />
			<BuildOutputInPackage Include="@(CredentialsActivitiesResources)">
				<TargetPath>%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
			</BuildOutputInPackage>
		</ItemGroup>
		<ItemGroup>
			<BuildOutputInPackage Include="$(OutputPath)UiPath.Credentials.Activities.ViewModels.dll" />
		</ItemGroup>
    <!--Coded workflow API files-->
    <ItemGroup Label="AddCodedWorkflowAPI">
      <BuildOutputInPackage Include="$(OutputPath)UiPath.Credentials.Activities.API.dll" />
      <BuildOutputInPackage Include="$(OutputPath)UiPath.Credentials.Activities.API.xml" />
    </ItemGroup>
	</Target>
	<ItemGroup>
		<PackageReference Include="CredentialManagement.Standard" Version="1.0.4" />
		<PackageReference Include="System.Drawing.Common" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\..\Credentials\UiPath.Credentials.Activities.ViewModels\UiPath.Credentials.Activities.ViewModels.csproj">
			<PrivateAssets>All</PrivateAssets>
		</ProjectReference>
    <ProjectReference Include="..\..\Credentials\UiPath.Credentials.Activities\UiPath.Credentials.Activities.csproj">
      <PrivateAssets>All</PrivateAssets>
    </ProjectReference>
    <ProjectReference Include="..\..\Credentials\UiPath.Credentials.Activities.API\UiPath.Credentials.Activities.API.csproj">
      <PrivateAssets>All</PrivateAssets>
    </ProjectReference>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="$(ConfigurationName) == Debug">
		<Exec Command="if exist &quot;$(ProjectDir)..\..\Output\Activities\Packages\UiPath.Credentials.*&quot; del &quot;$(ProjectDir)..\..\Output\Activities\Packages\UiPath.Credentials.*&quot;&#xD;&#xA;&#xD;&#xA;&quot;powershell.exe&quot; -file &quot;$(ProjectDir)..\..\Tools\net.sdk\pack-project.ps1&quot; -projectPath &quot;$(ProjectPath)&quot; -outputPath &quot;$(ProjectDir)..\..\Output\Activities\Packages&quot; -suffix &quot;dev&quot;" />
	</Target>
</Project>