<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop" ToolsVersion="Current">
  <PropertyGroup>
    <TargetFrameworks>$(WindowsFramework)</TargetFrameworks>
    <OutputPath>$(ProjectDir)..\..\Output\Activities\Database\</OutputPath>
    <UseWPF>true</UseWPF>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <Platforms>AnyCPU;x86;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Activities" />
    <PackageReference Include="UiPath.Workflow" />
    <PackageReference Include="System.Activities.Core.Presentation" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" />

    <!--Dependencies override to solve FOSSA issues-->
    <PackageReference Include="System.Formats.Asn1" />
  </ItemGroup>
	
  <ItemGroup>
    <Compile Remove="Dialogs\DataConnectionConfiguration.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions"/>
    <PackageReference Include="UiPath.Activities.Api" />
	<PackageReference Include="UiPath.Activities.Contracts" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\UiPath.Database.Activities.Design.fr.resx">
      <DependentUpon>UiPath.Database.Activities.Design.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\UiPath.Database.Activities.Design.ja.resx">
      <DependentUpon>UiPath.Database.Activities.Design.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\UiPath.Database.Activities.Design.ru.resx">
      <DependentUpon>UiPath.Database.Activities.Design.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\UiPath.Database.Activities.Design.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>UiPath.Database.Activities.Design.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ConnectionDialog\UiPath.Data.ConnectionUI.Dialog\UiPath.Data.ConnectionUI.Dialog.csproj" />
    <ProjectReference Include="..\UiPath.Database.Activities\UiPath.Database.Activities.csproj" />
    <ProjectReference Include="..\UiPath.Database\UiPath.Database.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\UiPath.Database.Activities.Design.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>UiPath.Database.Activities.Design.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Page Update="ExecuteNonQueryDesigner.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
    </Page>
  </ItemGroup>
</Project>