<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="Current">
    <PropertyGroup>
        <TargetFrameworks>$(PortableFramework);$(WindowsFramework)</TargetFrameworks>
        <OutputPath>..\..\Output\Activities\Database\</OutputPath>
        <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
        <PreserveCompilationContext>true</PreserveCompilationContext>
        <Platforms>AnyCPU;x86;x64</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="System.Data.Odbc" />
        <PackageReference Include="System.Data.OleDb" />
        <PackageReference Include="Microsoft.Data.Sqlite" />
        <PackageReference Include="UiPath.Workflow" />
        <PackageReference Include="Oracle.ManagedDataAccess.Core" />
        <PackageReference Include="Microsoft.Data.SqlClient" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="UiPath.Activities.Api" PrivateAssets="All" />
        <!--Dependencies override to solve FOSSA issues-->
        <PackageReference Include="System.Formats.Asn1" />
        <PackageReference Include="Azure.Identity" />
    </ItemGroup>
    <ItemGroup>
        <Compile Update="Properties\UiPath.Database.Designer.cs">
            <AutoGen>True</AutoGen>
            <DesignTime>True</DesignTime>
            <DependentUpon>UiPath.Database.resx</DependentUpon>
        </Compile>
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Update="Properties\UiPath.Database.*.resx">
            <DependentUpon>UiPath.Database.resx</DependentUpon>
        </EmbeddedResource>
        <EmbeddedResource Update="Properties\UiPath.Database.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>UiPath.Database.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>
</Project>