//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UiPath.Python.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UiPath_Python_Activities {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiPath_Python_Activities() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UiPath.Python.Activities.Properties.UiPath.Python.Activities", typeof(UiPath_Python_Activities).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python script content.
        /// </summary>
        internal static string CodeDescription {
            get {
                return ResourceManager.GetString("CodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string CodeNameDisplayName {
            get {
                return ResourceManager.GetString("CodeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error converting Python object.
        /// </summary>
        internal static string ConvertException {
            get {
                return ResourceManager.GetString("ConvertException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        internal static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the .NET type from a PythonObject.
        /// </summary>
        internal static string GetObjectDescription {
            get {
                return ResourceManager.GetString("GetObjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Python Object.
        /// </summary>
        internal static string GetObjectNameDisplayName {
            get {
                return ResourceManager.GetString("GetObjectNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The .NET type corresponding to Python object.
        /// </summary>
        internal static string GetObjectResultDescription {
            get {
                return ResourceManager.GetString("GetObjectResultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance of Python object.
        /// </summary>
        internal static string InstanceDescription {
            get {
                return ResourceManager.GetString("InstanceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance.
        /// </summary>
        internal static string InstanceNameDisplayName {
            get {
                return ResourceManager.GetString("InstanceNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid method name.
        /// </summary>
        internal static string InvalidMethodNameException {
            get {
                return ResourceManager.GetString("InvalidMethodNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified Python path is not valid: {0}.
        /// </summary>
        internal static string InvalidPathException {
            get {
                return ResourceManager.GetString("InvalidPathException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected version {0} is different from the version found {1}.
        /// </summary>
        internal static string InvalidVersionException {
            get {
                return ResourceManager.GetString("InvalidVersionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error invoking Python method.
        /// </summary>
        internal static string InvokeException {
            get {
                return ResourceManager.GetString("InvokeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke Python method.
        /// </summary>
        internal static string InvokeMethodDescription {
            get {
                return ResourceManager.GetString("InvokeMethodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke Python Method.
        /// </summary>
        internal static string InvokeMethodNameDisplayName {
            get {
                return ResourceManager.GetString("InvokeMethodNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loads and executes a Python script.
        /// </summary>
        internal static string LoadScriptDescription {
            get {
                return ResourceManager.GetString("LoadScriptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading Python script.
        /// </summary>
        internal static string LoadScriptException {
            get {
                return ResourceManager.GetString("LoadScriptException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Python Script.
        /// </summary>
        internal static string LoadScriptNameDisplayName {
            get {
                return ResourceManager.GetString("LoadScriptNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the method to be invoked.
        /// </summary>
        internal static string MethodNameDescription {
            get {
                return ResourceManager.GetString("MethodNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameDisplayName {
            get {
                return ResourceManager.GetString("NameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No code/script specified.
        /// </summary>
        internal static string NoScriptSpecifiedException {
            get {
                return ResourceManager.GetString("NoScriptSpecifiedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string OutputDisplayName {
            get {
                return ResourceManager.GetString("OutputDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input parameters for Python script.
        /// </summary>
        internal static string ParametersDescription {
            get {
                return ResourceManager.GetString("ParametersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputParameters.
        /// </summary>
        internal static string ParametersNameDisplayName {
            get {
                return ResourceManager.GetString("ParametersNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python home path.
        /// </summary>
        internal static string PathDescription {
            get {
                return ResourceManager.GetString("PathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string PathNameDisplayName {
            get {
                return ResourceManager.GetString("PathNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python engine session was not found.
        /// </summary>
        internal static string PythonEngineNotFoundException {
            get {
                return ResourceManager.GetString("PythonEngineNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing Python engine.
        /// </summary>
        internal static string PythonInitializeException {
            get {
                return ResourceManager.GetString("PythonInitializeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python object to extract value from.
        /// </summary>
        internal static string PythonObjectDescription {
            get {
                return ResourceManager.GetString("PythonObjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PythonObject.
        /// </summary>
        internal static string PythonObjectNameDisplayName {
            get {
                return ResourceManager.GetString("PythonObjectNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python activities container.
        /// </summary>
        internal static string PythonScopeDescription {
            get {
                return ResourceManager.GetString("PythonScopeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python Scope.
        /// </summary>
        internal static string PythonScopeNameDisplayName {
            get {
                return ResourceManager.GetString("PythonScopeNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result of script invocation.
        /// </summary>
        internal static string ResultDescription {
            get {
                return ResourceManager.GetString("ResultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string ResultNameDisplayName {
            get {
                return ResourceManager.GetString("ResultNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke Python script activity.
        /// </summary>
        internal static string RunScriptDescription {
            get {
                return ResourceManager.GetString("RunScriptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error running Python script.
        /// </summary>
        internal static string RunScriptException {
            get {
                return ResourceManager.GetString("RunScriptException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Python Script.
        /// </summary>
        internal static string RunScriptNameDisplayName {
            get {
                return ResourceManager.GetString("RunScriptNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full path to Python script file.
        /// </summary>
        internal static string ScriptFileDescription {
            get {
                return ResourceManager.GetString("ScriptFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string ScriptFileNameDisplayName {
            get {
                return ResourceManager.GetString("ScriptFileNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified script file was not found.
        /// </summary>
        internal static string ScriptFileNotFoundException {
            get {
                return ResourceManager.GetString("ScriptFileNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the Python runtime platform.
        /// </summary>
        internal static string TargetPlatformDescription {
            get {
                return ResourceManager.GetString("TargetPlatformDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string TargetPlatformDisplayName {
            get {
                return ResourceManager.GetString("TargetPlatformDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity is valid only inside {0}.
        /// </summary>
        internal static string ValidateParentError {
            get {
                return ResourceManager.GetString("ValidateParentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python version.
        /// </summary>
        internal static string VersionDescription {
            get {
                return ResourceManager.GetString("VersionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string VersionNameDisplayName {
            get {
                return ResourceManager.GetString("VersionNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkingFolder.
        /// </summary>
        internal static string WorkingFolder {
            get {
                return ResourceManager.GetString("WorkingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used to specify the working folder of the scripts executing under the current scope.
        /// </summary>
        internal static string WorkingFolderDescription {
            get {
                return ResourceManager.GetString("WorkingFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkingFolder path is not valid.
        /// </summary>
        internal static string WorkingFolderPathInvalid {
            get {
                return ResourceManager.GetString("WorkingFolderPathInvalid", resourceCulture);
            }
        }
    }
}
